/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.container;

import com.google.inject.Inject;
import com.tencent.ads.ApiContainer;
import com.tencent.ads.ApiException;
import com.tencent.ads.anno.*;
import com.tencent.ads.api.BarrageRecommendApi;
import com.tencent.ads.exception.TencentAdsResponseException;
import com.tencent.ads.model.BarrageRecommendGetResponse;
import com.tencent.ads.model.BarrageRecommendGetResponseData;
import java.util.List;

public class BarrageRecommendApiContainer extends ApiContainer {

  @Inject BarrageRecommendApi api;

  /**
   * 查询运营推荐弹幕列表
   *
   * @param accountId (required)
   * @param fields 返回参数的字段列表 (optional)
   * @return BarrageRecommendGetResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   */
  public BarrageRecommendGetResponseData barrageRecommendGet(Long accountId, List<String> fields)
      throws ApiException, TencentAdsResponseException {
    BarrageRecommendGetResponse resp = api.barrageRecommendGet(accountId, fields);
    handleResponse(gson.toJson(resp));
    return resp.getData();
  }
}
