/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.container;

import com.google.inject.Inject;
import com.tencent.ads.ApiContainer;
import com.tencent.ads.ApiException;
import com.tencent.ads.api.ComplianceValidationApi;
import com.tencent.ads.model.ComplianceValidationGetRequest;
import com.tencent.ads.model.ComplianceValidationGetResponse;
import com.tencent.ads.model.ComplianceValidationGetResponseData;


public class ComplianceValidationApiContainer extends ApiContainer {

  @Inject
  ComplianceValidationApi api;


  /**
   * 获取广告素材预审结果
   *
   * @param data (required)
   * @return ComplianceValidationGetResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   * response body
   */
  public ComplianceValidationGetResponseData complianceValidationGet(
      ComplianceValidationGetRequest data) throws ApiException {
    ComplianceValidationGetResponse resp = api.complianceValidationGet(data);
    handleResponse(gson.toJson(resp));
    return resp.getData();
  }


}
