/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 返回结构 */
@ApiModel(description = "返回结构")
public class AdvertiserGetListStruct {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("daily_budget")
  private Long dailyBudget = null;

  @SerializedName("system_status")
  private CustomerSystemStatus systemStatus = null;

  @SerializedName("reject_message")
  private String rejectMessage = null;

  @SerializedName("corporation_name")
  private String corporationName = null;

  @SerializedName("corporation_licence")
  private String corporationLicence = null;

  @SerializedName("certification_image_id")
  private String certificationImageId = null;

  @SerializedName("certification_image")
  private String certificationImage = null;

  @SerializedName("individual_qualification")
  private IndividualQualification individualQualification = null;

  @SerializedName("system_industry_id")
  private Long systemIndustryId = null;

  @SerializedName("customized_industry")
  private String customizedIndustry = null;

  @SerializedName("introduction_url")
  private String introductionUrl = null;

  @SerializedName("corporate_brand_name")
  private String corporateBrandName = null;

  @SerializedName("contact_person")
  private String contactPerson = null;

  @SerializedName("contact_person_email")
  private String contactPersonEmail = null;

  @SerializedName("contact_person_telephone")
  private String contactPersonTelephone = null;

  @SerializedName("contact_person_mobile")
  private String contactPersonMobile = null;

  @SerializedName("websites")
  private List<WebsiteReadStruct> websites = null;

  @SerializedName("mdm_id")
  private Long mdmId = null;

  @SerializedName("mdm_name")
  private String mdmName = null;

  @SerializedName("agency_account_id")
  private Long agencyAccountId = null;

  @SerializedName("operators")
  private List<AdvertiserOperatorStruct> operators = null;

  @SerializedName("memo")
  private String memo = null;

  @SerializedName("area_code")
  private Long areaCode = null;

  public AdvertiserGetListStruct accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public AdvertiserGetListStruct dailyBudget(Long dailyBudget) {
    this.dailyBudget = dailyBudget;
    return this;
  }

  /**
   * Get dailyBudget
   *
   * @return dailyBudget
   */
  @ApiModelProperty(value = "")
  public Long getDailyBudget() {
    return dailyBudget;
  }

  public void setDailyBudget(Long dailyBudget) {
    this.dailyBudget = dailyBudget;
  }

  public AdvertiserGetListStruct systemStatus(CustomerSystemStatus systemStatus) {
    this.systemStatus = systemStatus;
    return this;
  }

  /**
   * Get systemStatus
   *
   * @return systemStatus
   */
  @ApiModelProperty(value = "")
  public CustomerSystemStatus getSystemStatus() {
    return systemStatus;
  }

  public void setSystemStatus(CustomerSystemStatus systemStatus) {
    this.systemStatus = systemStatus;
  }

  public AdvertiserGetListStruct rejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
    return this;
  }

  /**
   * Get rejectMessage
   *
   * @return rejectMessage
   */
  @ApiModelProperty(value = "")
  public String getRejectMessage() {
    return rejectMessage;
  }

  public void setRejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
  }

  public AdvertiserGetListStruct corporationName(String corporationName) {
    this.corporationName = corporationName;
    return this;
  }

  /**
   * Get corporationName
   *
   * @return corporationName
   */
  @ApiModelProperty(value = "")
  public String getCorporationName() {
    return corporationName;
  }

  public void setCorporationName(String corporationName) {
    this.corporationName = corporationName;
  }

  public AdvertiserGetListStruct corporationLicence(String corporationLicence) {
    this.corporationLicence = corporationLicence;
    return this;
  }

  /**
   * Get corporationLicence
   *
   * @return corporationLicence
   */
  @ApiModelProperty(value = "")
  public String getCorporationLicence() {
    return corporationLicence;
  }

  public void setCorporationLicence(String corporationLicence) {
    this.corporationLicence = corporationLicence;
  }

  public AdvertiserGetListStruct certificationImageId(String certificationImageId) {
    this.certificationImageId = certificationImageId;
    return this;
  }

  /**
   * Get certificationImageId
   *
   * @return certificationImageId
   */
  @ApiModelProperty(value = "")
  public String getCertificationImageId() {
    return certificationImageId;
  }

  public void setCertificationImageId(String certificationImageId) {
    this.certificationImageId = certificationImageId;
  }

  public AdvertiserGetListStruct certificationImage(String certificationImage) {
    this.certificationImage = certificationImage;
    return this;
  }

  /**
   * Get certificationImage
   *
   * @return certificationImage
   */
  @ApiModelProperty(value = "")
  public String getCertificationImage() {
    return certificationImage;
  }

  public void setCertificationImage(String certificationImage) {
    this.certificationImage = certificationImage;
  }

  public AdvertiserGetListStruct individualQualification(
      IndividualQualification individualQualification) {
    this.individualQualification = individualQualification;
    return this;
  }

  /**
   * Get individualQualification
   *
   * @return individualQualification
   */
  @ApiModelProperty(value = "")
  public IndividualQualification getIndividualQualification() {
    return individualQualification;
  }

  public void setIndividualQualification(IndividualQualification individualQualification) {
    this.individualQualification = individualQualification;
  }

  public AdvertiserGetListStruct systemIndustryId(Long systemIndustryId) {
    this.systemIndustryId = systemIndustryId;
    return this;
  }

  /**
   * Get systemIndustryId
   *
   * @return systemIndustryId
   */
  @ApiModelProperty(value = "")
  public Long getSystemIndustryId() {
    return systemIndustryId;
  }

  public void setSystemIndustryId(Long systemIndustryId) {
    this.systemIndustryId = systemIndustryId;
  }

  public AdvertiserGetListStruct customizedIndustry(String customizedIndustry) {
    this.customizedIndustry = customizedIndustry;
    return this;
  }

  /**
   * Get customizedIndustry
   *
   * @return customizedIndustry
   */
  @ApiModelProperty(value = "")
  public String getCustomizedIndustry() {
    return customizedIndustry;
  }

  public void setCustomizedIndustry(String customizedIndustry) {
    this.customizedIndustry = customizedIndustry;
  }

  public AdvertiserGetListStruct introductionUrl(String introductionUrl) {
    this.introductionUrl = introductionUrl;
    return this;
  }

  /**
   * Get introductionUrl
   *
   * @return introductionUrl
   */
  @ApiModelProperty(value = "")
  public String getIntroductionUrl() {
    return introductionUrl;
  }

  public void setIntroductionUrl(String introductionUrl) {
    this.introductionUrl = introductionUrl;
  }

  public AdvertiserGetListStruct corporateBrandName(String corporateBrandName) {
    this.corporateBrandName = corporateBrandName;
    return this;
  }

  /**
   * Get corporateBrandName
   *
   * @return corporateBrandName
   */
  @ApiModelProperty(value = "")
  public String getCorporateBrandName() {
    return corporateBrandName;
  }

  public void setCorporateBrandName(String corporateBrandName) {
    this.corporateBrandName = corporateBrandName;
  }

  public AdvertiserGetListStruct contactPerson(String contactPerson) {
    this.contactPerson = contactPerson;
    return this;
  }

  /**
   * Get contactPerson
   *
   * @return contactPerson
   */
  @ApiModelProperty(value = "")
  public String getContactPerson() {
    return contactPerson;
  }

  public void setContactPerson(String contactPerson) {
    this.contactPerson = contactPerson;
  }

  public AdvertiserGetListStruct contactPersonEmail(String contactPersonEmail) {
    this.contactPersonEmail = contactPersonEmail;
    return this;
  }

  /**
   * Get contactPersonEmail
   *
   * @return contactPersonEmail
   */
  @ApiModelProperty(value = "")
  public String getContactPersonEmail() {
    return contactPersonEmail;
  }

  public void setContactPersonEmail(String contactPersonEmail) {
    this.contactPersonEmail = contactPersonEmail;
  }

  public AdvertiserGetListStruct contactPersonTelephone(String contactPersonTelephone) {
    this.contactPersonTelephone = contactPersonTelephone;
    return this;
  }

  /**
   * Get contactPersonTelephone
   *
   * @return contactPersonTelephone
   */
  @ApiModelProperty(value = "")
  public String getContactPersonTelephone() {
    return contactPersonTelephone;
  }

  public void setContactPersonTelephone(String contactPersonTelephone) {
    this.contactPersonTelephone = contactPersonTelephone;
  }

  public AdvertiserGetListStruct contactPersonMobile(String contactPersonMobile) {
    this.contactPersonMobile = contactPersonMobile;
    return this;
  }

  /**
   * Get contactPersonMobile
   *
   * @return contactPersonMobile
   */
  @ApiModelProperty(value = "")
  public String getContactPersonMobile() {
    return contactPersonMobile;
  }

  public void setContactPersonMobile(String contactPersonMobile) {
    this.contactPersonMobile = contactPersonMobile;
  }

  public AdvertiserGetListStruct websites(List<WebsiteReadStruct> websites) {
    this.websites = websites;
    return this;
  }

  public AdvertiserGetListStruct addWebsitesItem(WebsiteReadStruct websitesItem) {
    if (this.websites == null) {
      this.websites = new ArrayList<WebsiteReadStruct>();
    }
    this.websites.add(websitesItem);
    return this;
  }

  /**
   * Get websites
   *
   * @return websites
   */
  @ApiModelProperty(value = "")
  public List<WebsiteReadStruct> getWebsites() {
    return websites;
  }

  public void setWebsites(List<WebsiteReadStruct> websites) {
    this.websites = websites;
  }

  public AdvertiserGetListStruct mdmId(Long mdmId) {
    this.mdmId = mdmId;
    return this;
  }

  /**
   * Get mdmId
   *
   * @return mdmId
   */
  @ApiModelProperty(value = "")
  public Long getMdmId() {
    return mdmId;
  }

  public void setMdmId(Long mdmId) {
    this.mdmId = mdmId;
  }

  public AdvertiserGetListStruct mdmName(String mdmName) {
    this.mdmName = mdmName;
    return this;
  }

  /**
   * Get mdmName
   *
   * @return mdmName
   */
  @ApiModelProperty(value = "")
  public String getMdmName() {
    return mdmName;
  }

  public void setMdmName(String mdmName) {
    this.mdmName = mdmName;
  }

  public AdvertiserGetListStruct agencyAccountId(Long agencyAccountId) {
    this.agencyAccountId = agencyAccountId;
    return this;
  }

  /**
   * Get agencyAccountId
   *
   * @return agencyAccountId
   */
  @ApiModelProperty(value = "")
  public Long getAgencyAccountId() {
    return agencyAccountId;
  }

  public void setAgencyAccountId(Long agencyAccountId) {
    this.agencyAccountId = agencyAccountId;
  }

  public AdvertiserGetListStruct operators(List<AdvertiserOperatorStruct> operators) {
    this.operators = operators;
    return this;
  }

  public AdvertiserGetListStruct addOperatorsItem(AdvertiserOperatorStruct operatorsItem) {
    if (this.operators == null) {
      this.operators = new ArrayList<AdvertiserOperatorStruct>();
    }
    this.operators.add(operatorsItem);
    return this;
  }

  /**
   * Get operators
   *
   * @return operators
   */
  @ApiModelProperty(value = "")
  public List<AdvertiserOperatorStruct> getOperators() {
    return operators;
  }

  public void setOperators(List<AdvertiserOperatorStruct> operators) {
    this.operators = operators;
  }

  public AdvertiserGetListStruct memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * Get memo
   *
   * @return memo
   */
  @ApiModelProperty(value = "")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public AdvertiserGetListStruct areaCode(Long areaCode) {
    this.areaCode = areaCode;
    return this;
  }

  /**
   * Get areaCode
   *
   * @return areaCode
   */
  @ApiModelProperty(value = "")
  public Long getAreaCode() {
    return areaCode;
  }

  public void setAreaCode(Long areaCode) {
    this.areaCode = areaCode;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvertiserGetListStruct advertiserGetListStruct = (AdvertiserGetListStruct) o;
    return Objects.equals(this.accountId, advertiserGetListStruct.accountId)
        && Objects.equals(this.dailyBudget, advertiserGetListStruct.dailyBudget)
        && Objects.equals(this.systemStatus, advertiserGetListStruct.systemStatus)
        && Objects.equals(this.rejectMessage, advertiserGetListStruct.rejectMessage)
        && Objects.equals(this.corporationName, advertiserGetListStruct.corporationName)
        && Objects.equals(this.corporationLicence, advertiserGetListStruct.corporationLicence)
        && Objects.equals(this.certificationImageId, advertiserGetListStruct.certificationImageId)
        && Objects.equals(this.certificationImage, advertiserGetListStruct.certificationImage)
        && Objects.equals(
            this.individualQualification, advertiserGetListStruct.individualQualification)
        && Objects.equals(this.systemIndustryId, advertiserGetListStruct.systemIndustryId)
        && Objects.equals(this.customizedIndustry, advertiserGetListStruct.customizedIndustry)
        && Objects.equals(this.introductionUrl, advertiserGetListStruct.introductionUrl)
        && Objects.equals(this.corporateBrandName, advertiserGetListStruct.corporateBrandName)
        && Objects.equals(this.contactPerson, advertiserGetListStruct.contactPerson)
        && Objects.equals(this.contactPersonEmail, advertiserGetListStruct.contactPersonEmail)
        && Objects.equals(
            this.contactPersonTelephone, advertiserGetListStruct.contactPersonTelephone)
        && Objects.equals(this.contactPersonMobile, advertiserGetListStruct.contactPersonMobile)
        && Objects.equals(this.websites, advertiserGetListStruct.websites)
        && Objects.equals(this.mdmId, advertiserGetListStruct.mdmId)
        && Objects.equals(this.mdmName, advertiserGetListStruct.mdmName)
        && Objects.equals(this.agencyAccountId, advertiserGetListStruct.agencyAccountId)
        && Objects.equals(this.operators, advertiserGetListStruct.operators)
        && Objects.equals(this.memo, advertiserGetListStruct.memo)
        && Objects.equals(this.areaCode, advertiserGetListStruct.areaCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountId,
        dailyBudget,
        systemStatus,
        rejectMessage,
        corporationName,
        corporationLicence,
        certificationImageId,
        certificationImage,
        individualQualification,
        systemIndustryId,
        customizedIndustry,
        introductionUrl,
        corporateBrandName,
        contactPerson,
        contactPersonEmail,
        contactPersonTelephone,
        contactPersonMobile,
        websites,
        mdmId,
        mdmName,
        agencyAccountId,
        operators,
        memo,
        areaCode);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
