/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 返回结构 */
@ApiModel(description = "返回结构")
public class AgencyGetListStruct {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("corporation_name")
  private String corporationName = null;

  @SerializedName("system_status")
  private CustomerSystemStatus systemStatus = null;

  @SerializedName("reject_message")
  private String rejectMessage = null;

  @SerializedName("parent_agency_id")
  private Long parentAgencyId = null;

  @SerializedName("memo")
  private String memo = null;

  public AgencyGetListStruct accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public AgencyGetListStruct corporationName(String corporationName) {
    this.corporationName = corporationName;
    return this;
  }

  /**
   * Get corporationName
   *
   * @return corporationName
   */
  @ApiModelProperty(value = "")
  public String getCorporationName() {
    return corporationName;
  }

  public void setCorporationName(String corporationName) {
    this.corporationName = corporationName;
  }

  public AgencyGetListStruct systemStatus(CustomerSystemStatus systemStatus) {
    this.systemStatus = systemStatus;
    return this;
  }

  /**
   * Get systemStatus
   *
   * @return systemStatus
   */
  @ApiModelProperty(value = "")
  public CustomerSystemStatus getSystemStatus() {
    return systemStatus;
  }

  public void setSystemStatus(CustomerSystemStatus systemStatus) {
    this.systemStatus = systemStatus;
  }

  public AgencyGetListStruct rejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
    return this;
  }

  /**
   * Get rejectMessage
   *
   * @return rejectMessage
   */
  @ApiModelProperty(value = "")
  public String getRejectMessage() {
    return rejectMessage;
  }

  public void setRejectMessage(String rejectMessage) {
    this.rejectMessage = rejectMessage;
  }

  public AgencyGetListStruct parentAgencyId(Long parentAgencyId) {
    this.parentAgencyId = parentAgencyId;
    return this;
  }

  /**
   * Get parentAgencyId
   *
   * @return parentAgencyId
   */
  @ApiModelProperty(value = "")
  public Long getParentAgencyId() {
    return parentAgencyId;
  }

  public void setParentAgencyId(Long parentAgencyId) {
    this.parentAgencyId = parentAgencyId;
  }

  public AgencyGetListStruct memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * Get memo
   *
   * @return memo
   */
  @ApiModelProperty(value = "")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgencyGetListStruct agencyGetListStruct = (AgencyGetListStruct) o;
    return Objects.equals(this.accountId, agencyGetListStruct.accountId)
        && Objects.equals(this.corporationName, agencyGetListStruct.corporationName)
        && Objects.equals(this.systemStatus, agencyGetListStruct.systemStatus)
        && Objects.equals(this.rejectMessage, agencyGetListStruct.rejectMessage)
        && Objects.equals(this.parentAgencyId, agencyGetListStruct.parentAgencyId)
        && Objects.equals(this.memo, agencyGetListStruct.memo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountId, corporationName, systemStatus, rejectMessage, parentAgencyId, memo);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
