/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 关键词信息 */
@ApiModel(description = "关键词信息")
public class BidwordGetListStruct {
  @SerializedName("bidword_id")
  private Long bidwordId = null;

  @SerializedName("campaign_id")
  private Long campaignId = null;

  @SerializedName("adgroup_id")
  private Long adgroupId = null;

  @SerializedName("bidword")
  private String bidword = null;

  @SerializedName("bid_price")
  private Long bidPrice = null;

  @SerializedName("match_type")
  private BidwordMatchType matchType = null;

  @SerializedName("configured_status")
  private BidwordPauseType configuredStatus = null;

  @SerializedName("bidword_status")
  private BidwordStatus bidwordStatus = null;

  @SerializedName("use_group_price")
  private UseGroupPriceType useGroupPrice = null;

  @SerializedName("audit_msg")
  private String auditMsg = null;

  @SerializedName("created_time")
  private Long createdTime = null;

  @SerializedName("last_modified_time")
  private Long lastModifiedTime = null;

  @SerializedName("pc_landing_page_info")
  private List<BackupsJumpinfoStruct> pcLandingPageInfo = null;

  @SerializedName("mobile_landing_page_info")
  private List<BackupsJumpinfoStruct> mobileLandingPageInfo = null;

  public BidwordGetListStruct bidwordId(Long bidwordId) {
    this.bidwordId = bidwordId;
    return this;
  }

  /**
   * Get bidwordId
   *
   * @return bidwordId
   */
  @ApiModelProperty(value = "")
  public Long getBidwordId() {
    return bidwordId;
  }

  public void setBidwordId(Long bidwordId) {
    this.bidwordId = bidwordId;
  }

  public BidwordGetListStruct campaignId(Long campaignId) {
    this.campaignId = campaignId;
    return this;
  }

  /**
   * Get campaignId
   *
   * @return campaignId
   */
  @ApiModelProperty(value = "")
  public Long getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(Long campaignId) {
    this.campaignId = campaignId;
  }

  public BidwordGetListStruct adgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
    return this;
  }

  /**
   * Get adgroupId
   *
   * @return adgroupId
   */
  @ApiModelProperty(value = "")
  public Long getAdgroupId() {
    return adgroupId;
  }

  public void setAdgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
  }

  public BidwordGetListStruct bidword(String bidword) {
    this.bidword = bidword;
    return this;
  }

  /**
   * Get bidword
   *
   * @return bidword
   */
  @ApiModelProperty(value = "")
  public String getBidword() {
    return bidword;
  }

  public void setBidword(String bidword) {
    this.bidword = bidword;
  }

  public BidwordGetListStruct bidPrice(Long bidPrice) {
    this.bidPrice = bidPrice;
    return this;
  }

  /**
   * Get bidPrice
   *
   * @return bidPrice
   */
  @ApiModelProperty(value = "")
  public Long getBidPrice() {
    return bidPrice;
  }

  public void setBidPrice(Long bidPrice) {
    this.bidPrice = bidPrice;
  }

  public BidwordGetListStruct matchType(BidwordMatchType matchType) {
    this.matchType = matchType;
    return this;
  }

  /**
   * Get matchType
   *
   * @return matchType
   */
  @ApiModelProperty(value = "")
  public BidwordMatchType getMatchType() {
    return matchType;
  }

  public void setMatchType(BidwordMatchType matchType) {
    this.matchType = matchType;
  }

  public BidwordGetListStruct configuredStatus(BidwordPauseType configuredStatus) {
    this.configuredStatus = configuredStatus;
    return this;
  }

  /**
   * Get configuredStatus
   *
   * @return configuredStatus
   */
  @ApiModelProperty(value = "")
  public BidwordPauseType getConfiguredStatus() {
    return configuredStatus;
  }

  public void setConfiguredStatus(BidwordPauseType configuredStatus) {
    this.configuredStatus = configuredStatus;
  }

  public BidwordGetListStruct bidwordStatus(BidwordStatus bidwordStatus) {
    this.bidwordStatus = bidwordStatus;
    return this;
  }

  /**
   * Get bidwordStatus
   *
   * @return bidwordStatus
   */
  @ApiModelProperty(value = "")
  public BidwordStatus getBidwordStatus() {
    return bidwordStatus;
  }

  public void setBidwordStatus(BidwordStatus bidwordStatus) {
    this.bidwordStatus = bidwordStatus;
  }

  public BidwordGetListStruct useGroupPrice(UseGroupPriceType useGroupPrice) {
    this.useGroupPrice = useGroupPrice;
    return this;
  }

  /**
   * Get useGroupPrice
   *
   * @return useGroupPrice
   */
  @ApiModelProperty(value = "")
  public UseGroupPriceType getUseGroupPrice() {
    return useGroupPrice;
  }

  public void setUseGroupPrice(UseGroupPriceType useGroupPrice) {
    this.useGroupPrice = useGroupPrice;
  }

  public BidwordGetListStruct auditMsg(String auditMsg) {
    this.auditMsg = auditMsg;
    return this;
  }

  /**
   * Get auditMsg
   *
   * @return auditMsg
   */
  @ApiModelProperty(value = "")
  public String getAuditMsg() {
    return auditMsg;
  }

  public void setAuditMsg(String auditMsg) {
    this.auditMsg = auditMsg;
  }

  public BidwordGetListStruct createdTime(Long createdTime) {
    this.createdTime = createdTime;
    return this;
  }

  /**
   * Get createdTime
   *
   * @return createdTime
   */
  @ApiModelProperty(value = "")
  public Long getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(Long createdTime) {
    this.createdTime = createdTime;
  }

  public BidwordGetListStruct lastModifiedTime(Long lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

  /**
   * Get lastModifiedTime
   *
   * @return lastModifiedTime
   */
  @ApiModelProperty(value = "")
  public Long getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(Long lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }

  public BidwordGetListStruct pcLandingPageInfo(List<BackupsJumpinfoStruct> pcLandingPageInfo) {
    this.pcLandingPageInfo = pcLandingPageInfo;
    return this;
  }

  public BidwordGetListStruct addPcLandingPageInfoItem(
      BackupsJumpinfoStruct pcLandingPageInfoItem) {
    if (this.pcLandingPageInfo == null) {
      this.pcLandingPageInfo = new ArrayList<BackupsJumpinfoStruct>();
    }
    this.pcLandingPageInfo.add(pcLandingPageInfoItem);
    return this;
  }

  /**
   * Get pcLandingPageInfo
   *
   * @return pcLandingPageInfo
   */
  @ApiModelProperty(value = "")
  public List<BackupsJumpinfoStruct> getPcLandingPageInfo() {
    return pcLandingPageInfo;
  }

  public void setPcLandingPageInfo(List<BackupsJumpinfoStruct> pcLandingPageInfo) {
    this.pcLandingPageInfo = pcLandingPageInfo;
  }

  public BidwordGetListStruct mobileLandingPageInfo(
      List<BackupsJumpinfoStruct> mobileLandingPageInfo) {
    this.mobileLandingPageInfo = mobileLandingPageInfo;
    return this;
  }

  public BidwordGetListStruct addMobileLandingPageInfoItem(
      BackupsJumpinfoStruct mobileLandingPageInfoItem) {
    if (this.mobileLandingPageInfo == null) {
      this.mobileLandingPageInfo = new ArrayList<BackupsJumpinfoStruct>();
    }
    this.mobileLandingPageInfo.add(mobileLandingPageInfoItem);
    return this;
  }

  /**
   * Get mobileLandingPageInfo
   *
   * @return mobileLandingPageInfo
   */
  @ApiModelProperty(value = "")
  public List<BackupsJumpinfoStruct> getMobileLandingPageInfo() {
    return mobileLandingPageInfo;
  }

  public void setMobileLandingPageInfo(List<BackupsJumpinfoStruct> mobileLandingPageInfo) {
    this.mobileLandingPageInfo = mobileLandingPageInfo;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BidwordGetListStruct bidwordGetListStruct = (BidwordGetListStruct) o;
    return Objects.equals(this.bidwordId, bidwordGetListStruct.bidwordId)
        && Objects.equals(this.campaignId, bidwordGetListStruct.campaignId)
        && Objects.equals(this.adgroupId, bidwordGetListStruct.adgroupId)
        && Objects.equals(this.bidword, bidwordGetListStruct.bidword)
        && Objects.equals(this.bidPrice, bidwordGetListStruct.bidPrice)
        && Objects.equals(this.matchType, bidwordGetListStruct.matchType)
        && Objects.equals(this.configuredStatus, bidwordGetListStruct.configuredStatus)
        && Objects.equals(this.bidwordStatus, bidwordGetListStruct.bidwordStatus)
        && Objects.equals(this.useGroupPrice, bidwordGetListStruct.useGroupPrice)
        && Objects.equals(this.auditMsg, bidwordGetListStruct.auditMsg)
        && Objects.equals(this.createdTime, bidwordGetListStruct.createdTime)
        && Objects.equals(this.lastModifiedTime, bidwordGetListStruct.lastModifiedTime)
        && Objects.equals(this.pcLandingPageInfo, bidwordGetListStruct.pcLandingPageInfo)
        && Objects.equals(this.mobileLandingPageInfo, bidwordGetListStruct.mobileLandingPageInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        bidwordId,
        campaignId,
        adgroupId,
        bidword,
        bidPrice,
        matchType,
        configuredStatus,
        bidwordStatus,
        useGroupPrice,
        auditMsg,
        createdTime,
        lastModifiedTime,
        pcLandingPageInfo,
        mobileLandingPageInfo);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
