/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 链路节点信息 */
@ApiModel(description = "链路节点信息")
public class ConversionLinkAssetNodeStruct {
  @SerializedName("conversion_link_node_id")
  private Long conversionLinkNodeId = null;

  @SerializedName("conversion_link_node_name")
  private String conversionLinkNodeName = null;

  @SerializedName("conversion_link_node_index")
  private Long conversionLinkNodeIndex = null;

  @SerializedName("conversion_link_action_type")
  private ActionType conversionLinkActionType = null;

  @SerializedName("carrier_id")
  private Long carrierId = null;

  @SerializedName("carrier_name")
  private String carrierName = null;

  @SerializedName("og_id")
  private List<Long> ogId = null;

  @SerializedName("og_list")
  private List<NodeOgStruct> ogList = null;

  @SerializedName("roi_og_id")
  private List<Long> roiOgId = null;

  @SerializedName("roi_og_list")
  private List<NodeRoiOgStruct> roiOgList = null;

  @SerializedName("conversion_info")
  private List<ConvInfoStruct> conversionInfo = null;

  @SerializedName("og_status")
  private Long ogStatus = null;

  @SerializedName("node_status")
  private Long nodeStatus = null;

  public ConversionLinkAssetNodeStruct conversionLinkNodeId(Long conversionLinkNodeId) {
    this.conversionLinkNodeId = conversionLinkNodeId;
    return this;
  }

  /**
   * Get conversionLinkNodeId
   *
   * @return conversionLinkNodeId
   */
  @ApiModelProperty(value = "")
  public Long getConversionLinkNodeId() {
    return conversionLinkNodeId;
  }

  public void setConversionLinkNodeId(Long conversionLinkNodeId) {
    this.conversionLinkNodeId = conversionLinkNodeId;
  }

  public ConversionLinkAssetNodeStruct conversionLinkNodeName(String conversionLinkNodeName) {
    this.conversionLinkNodeName = conversionLinkNodeName;
    return this;
  }

  /**
   * Get conversionLinkNodeName
   *
   * @return conversionLinkNodeName
   */
  @ApiModelProperty(value = "")
  public String getConversionLinkNodeName() {
    return conversionLinkNodeName;
  }

  public void setConversionLinkNodeName(String conversionLinkNodeName) {
    this.conversionLinkNodeName = conversionLinkNodeName;
  }

  public ConversionLinkAssetNodeStruct conversionLinkNodeIndex(Long conversionLinkNodeIndex) {
    this.conversionLinkNodeIndex = conversionLinkNodeIndex;
    return this;
  }

  /**
   * Get conversionLinkNodeIndex
   *
   * @return conversionLinkNodeIndex
   */
  @ApiModelProperty(value = "")
  public Long getConversionLinkNodeIndex() {
    return conversionLinkNodeIndex;
  }

  public void setConversionLinkNodeIndex(Long conversionLinkNodeIndex) {
    this.conversionLinkNodeIndex = conversionLinkNodeIndex;
  }

  public ConversionLinkAssetNodeStruct conversionLinkActionType(
      ActionType conversionLinkActionType) {
    this.conversionLinkActionType = conversionLinkActionType;
    return this;
  }

  /**
   * Get conversionLinkActionType
   *
   * @return conversionLinkActionType
   */
  @ApiModelProperty(value = "")
  public ActionType getConversionLinkActionType() {
    return conversionLinkActionType;
  }

  public void setConversionLinkActionType(ActionType conversionLinkActionType) {
    this.conversionLinkActionType = conversionLinkActionType;
  }

  public ConversionLinkAssetNodeStruct carrierId(Long carrierId) {
    this.carrierId = carrierId;
    return this;
  }

  /**
   * Get carrierId
   *
   * @return carrierId
   */
  @ApiModelProperty(value = "")
  public Long getCarrierId() {
    return carrierId;
  }

  public void setCarrierId(Long carrierId) {
    this.carrierId = carrierId;
  }

  public ConversionLinkAssetNodeStruct carrierName(String carrierName) {
    this.carrierName = carrierName;
    return this;
  }

  /**
   * Get carrierName
   *
   * @return carrierName
   */
  @ApiModelProperty(value = "")
  public String getCarrierName() {
    return carrierName;
  }

  public void setCarrierName(String carrierName) {
    this.carrierName = carrierName;
  }

  public ConversionLinkAssetNodeStruct ogId(List<Long> ogId) {
    this.ogId = ogId;
    return this;
  }

  public ConversionLinkAssetNodeStruct addOgIdItem(Long ogIdItem) {
    if (this.ogId == null) {
      this.ogId = new ArrayList<Long>();
    }
    this.ogId.add(ogIdItem);
    return this;
  }

  /**
   * Get ogId
   *
   * @return ogId
   */
  @ApiModelProperty(value = "")
  public List<Long> getOgId() {
    return ogId;
  }

  public void setOgId(List<Long> ogId) {
    this.ogId = ogId;
  }

  public ConversionLinkAssetNodeStruct ogList(List<NodeOgStruct> ogList) {
    this.ogList = ogList;
    return this;
  }

  public ConversionLinkAssetNodeStruct addOgListItem(NodeOgStruct ogListItem) {
    if (this.ogList == null) {
      this.ogList = new ArrayList<NodeOgStruct>();
    }
    this.ogList.add(ogListItem);
    return this;
  }

  /**
   * Get ogList
   *
   * @return ogList
   */
  @ApiModelProperty(value = "")
  public List<NodeOgStruct> getOgList() {
    return ogList;
  }

  public void setOgList(List<NodeOgStruct> ogList) {
    this.ogList = ogList;
  }

  public ConversionLinkAssetNodeStruct roiOgId(List<Long> roiOgId) {
    this.roiOgId = roiOgId;
    return this;
  }

  public ConversionLinkAssetNodeStruct addRoiOgIdItem(Long roiOgIdItem) {
    if (this.roiOgId == null) {
      this.roiOgId = new ArrayList<Long>();
    }
    this.roiOgId.add(roiOgIdItem);
    return this;
  }

  /**
   * Get roiOgId
   *
   * @return roiOgId
   */
  @ApiModelProperty(value = "")
  public List<Long> getRoiOgId() {
    return roiOgId;
  }

  public void setRoiOgId(List<Long> roiOgId) {
    this.roiOgId = roiOgId;
  }

  public ConversionLinkAssetNodeStruct roiOgList(List<NodeRoiOgStruct> roiOgList) {
    this.roiOgList = roiOgList;
    return this;
  }

  public ConversionLinkAssetNodeStruct addRoiOgListItem(NodeRoiOgStruct roiOgListItem) {
    if (this.roiOgList == null) {
      this.roiOgList = new ArrayList<NodeRoiOgStruct>();
    }
    this.roiOgList.add(roiOgListItem);
    return this;
  }

  /**
   * Get roiOgList
   *
   * @return roiOgList
   */
  @ApiModelProperty(value = "")
  public List<NodeRoiOgStruct> getRoiOgList() {
    return roiOgList;
  }

  public void setRoiOgList(List<NodeRoiOgStruct> roiOgList) {
    this.roiOgList = roiOgList;
  }

  public ConversionLinkAssetNodeStruct conversionInfo(List<ConvInfoStruct> conversionInfo) {
    this.conversionInfo = conversionInfo;
    return this;
  }

  public ConversionLinkAssetNodeStruct addConversionInfoItem(ConvInfoStruct conversionInfoItem) {
    if (this.conversionInfo == null) {
      this.conversionInfo = new ArrayList<ConvInfoStruct>();
    }
    this.conversionInfo.add(conversionInfoItem);
    return this;
  }

  /**
   * Get conversionInfo
   *
   * @return conversionInfo
   */
  @ApiModelProperty(value = "")
  public List<ConvInfoStruct> getConversionInfo() {
    return conversionInfo;
  }

  public void setConversionInfo(List<ConvInfoStruct> conversionInfo) {
    this.conversionInfo = conversionInfo;
  }

  public ConversionLinkAssetNodeStruct ogStatus(Long ogStatus) {
    this.ogStatus = ogStatus;
    return this;
  }

  /**
   * Get ogStatus
   *
   * @return ogStatus
   */
  @ApiModelProperty(value = "")
  public Long getOgStatus() {
    return ogStatus;
  }

  public void setOgStatus(Long ogStatus) {
    this.ogStatus = ogStatus;
  }

  public ConversionLinkAssetNodeStruct nodeStatus(Long nodeStatus) {
    this.nodeStatus = nodeStatus;
    return this;
  }

  /**
   * Get nodeStatus
   *
   * @return nodeStatus
   */
  @ApiModelProperty(value = "")
  public Long getNodeStatus() {
    return nodeStatus;
  }

  public void setNodeStatus(Long nodeStatus) {
    this.nodeStatus = nodeStatus;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversionLinkAssetNodeStruct conversionLinkAssetNodeStruct = (ConversionLinkAssetNodeStruct) o;
    return Objects.equals(
            this.conversionLinkNodeId, conversionLinkAssetNodeStruct.conversionLinkNodeId)
        && Objects.equals(
            this.conversionLinkNodeName, conversionLinkAssetNodeStruct.conversionLinkNodeName)
        && Objects.equals(
            this.conversionLinkNodeIndex, conversionLinkAssetNodeStruct.conversionLinkNodeIndex)
        && Objects.equals(
            this.conversionLinkActionType, conversionLinkAssetNodeStruct.conversionLinkActionType)
        && Objects.equals(this.carrierId, conversionLinkAssetNodeStruct.carrierId)
        && Objects.equals(this.carrierName, conversionLinkAssetNodeStruct.carrierName)
        && Objects.equals(this.ogId, conversionLinkAssetNodeStruct.ogId)
        && Objects.equals(this.ogList, conversionLinkAssetNodeStruct.ogList)
        && Objects.equals(this.roiOgId, conversionLinkAssetNodeStruct.roiOgId)
        && Objects.equals(this.roiOgList, conversionLinkAssetNodeStruct.roiOgList)
        && Objects.equals(this.conversionInfo, conversionLinkAssetNodeStruct.conversionInfo)
        && Objects.equals(this.ogStatus, conversionLinkAssetNodeStruct.ogStatus)
        && Objects.equals(this.nodeStatus, conversionLinkAssetNodeStruct.nodeStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        conversionLinkNodeId,
        conversionLinkNodeName,
        conversionLinkNodeIndex,
        conversionLinkActionType,
        carrierId,
        carrierName,
        ogId,
        ogList,
        roiOgId,
        roiOgList,
        conversionInfo,
        ogStatus,
        nodeStatus);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
