/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;


import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 流量覆盖披露规则跳转类型 */
@JsonAdapter(CoverageActionType.Adapter.class)
public enum CoverageActionType {
  UNKNOWN("UNKNOWN"),

  VIDEO_DURATION_60("VIDEO_DURATION_60"),

  FLOATING_ZONE_OPEN_IMAGE_TEXT("FLOATING_ZONE_OPEN_IMAGE_TEXT"),

  FLOATING_ZONE_TYPE_SWITCH_IMAGE_TEXT("FLOATING_ZONE_TYPE_SWITCH_IMAGE_TEXT"),

  BRAND_JUMP_TYPE_WECHAT_CHANNELS_PROFILE("BRAND_JUMP_TYPE_WECHAT_CHANNELS_PROFILE"),

  BRAND_JUMP_TYPE_OPEN_SELECT_FIRST("BRAND_JUMP_TYPE_OPEN_SELECT_FIRST"),

  ADD_NEW_TEMPLATE_ID_720("ADD_NEW_TEMPLATE_ID_720"),

  ADD_NEW_TEMPLATE_ID_721("ADD_NEW_TEMPLATE_ID_721"),

  ADD_NEW_TEMPLATE_ID_711("ADD_NEW_TEMPLATE_ID_711"),

  ADD_NEW_TEMPLATE_ID_712("ADD_NEW_TEMPLATE_ID_712"),

  ADD_NEW_TEMPLATE_ID_925("ADD_NEW_TEMPLATE_ID_925"),

  VIDEO_DURATION_180("VIDEO_DURATION_180"),

  BRAND_JUMP_TYPE_WECHAT_OFFICIAL_ACCOUNT_DETAIL("BRAND_JUMP_TYPE_WECHAT_OFFICIAL_ACCOUNT_DETAIL"),

  BRAND_JUMP_TYPE_H5_PROFILE("BRAND_JUMP_TYPE_H5_PROFILE"),

  BRAND_JUMP_TYPE_SEARCH_BRAND_AREA("BRAND_JUMP_TYPE_SEARCH_BRAND_AREA"),

  BRAND_JUMP_TYPE_TYPE_BRAND("BRAND_JUMP_TYPE_TYPE_BRAND"),

  ADD_VIDEO_SIZE_16_9("ADD_VIDEO_SIZE_16_9"),

  ADD_VIDEO_SIZE_9_16("ADD_VIDEO_SIZE_9_16"),

  ADD_IMAGE_SIZE_16_9("ADD_IMAGE_SIZE_16_9"),

  ADD_IMAGE_SIZE_9_16("ADD_IMAGE_SIZE_9_16"),

  ADD_IMAGE_SIZE_20_7("ADD_IMAGE_SIZE_20_7"),

  LANDING_PAGE_USE_MULTI_SLOT("LANDING_PAGE_USE_MULTI_SLOT"),

  ADD_AUDIO("ADD_AUDIO");

  private String value;

  CoverageActionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CoverageActionType fromValue(String text) {
    for (CoverageActionType b : CoverageActionType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CoverageActionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CoverageActionType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CoverageActionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CoverageActionType.fromValue(String.valueOf(value));
    }
  }
}
