/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 流量覆盖披露引导各创意操作列表 */
@ApiModel(description = "流量覆盖披露引导各创意操作列表")
public class CreativeSuggestActionItem {
  @SerializedName("suggest_action_item")
  private List<SuggestActionItem> suggestActionItem = null;

  public CreativeSuggestActionItem suggestActionItem(List<SuggestActionItem> suggestActionItem) {
    this.suggestActionItem = suggestActionItem;
    return this;
  }

  public CreativeSuggestActionItem addSuggestActionItemItem(
      SuggestActionItem suggestActionItemItem) {
    if (this.suggestActionItem == null) {
      this.suggestActionItem = new ArrayList<SuggestActionItem>();
    }
    this.suggestActionItem.add(suggestActionItemItem);
    return this;
  }

  /**
   * Get suggestActionItem
   *
   * @return suggestActionItem
   */
  @ApiModelProperty(value = "")
  public List<SuggestActionItem> getSuggestActionItem() {
    return suggestActionItem;
  }

  public void setSuggestActionItem(List<SuggestActionItem> suggestActionItem) {
    this.suggestActionItem = suggestActionItem;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreativeSuggestActionItem creativeSuggestActionItem = (CreativeSuggestActionItem) o;
    return Objects.equals(this.suggestActionItem, creativeSuggestActionItem.suggestActionItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suggestActionItem);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
