/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;


import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 浮层卡片类型 */
@JsonAdapter(CreativeFloatingZoneType.Adapter.class)
public enum CreativeFloatingZoneType {
  UNKNOWN("FLOATING_ZONE_TYPE_UNKNOWN"),

  IMAGE_TEXT("FLOATING_ZONE_TYPE_IMAGE_TEXT"),

  SINGLE_IMAGE("FLOATING_ZONE_TYPE_SINGLE_IMAGE"),

  MULTI_BUTTON("FLOATING_ZONE_TYPE_MULTI_BUTTON"),

  SLIDER_CARD("FLOATING_ZONE_TYPE_SLIDER_CARD");

  private String value;

  CreativeFloatingZoneType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CreativeFloatingZoneType fromValue(String text) {
    for (CreativeFloatingZoneType b : CreativeFloatingZoneType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CreativeFloatingZoneType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CreativeFloatingZoneType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CreativeFloatingZoneType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CreativeFloatingZoneType.fromValue(String.valueOf(value));
    }
  }
}
