/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 返回结构 */
@ApiModel(description = "返回结构")
public class DailyBalanceReportGetListStruct {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("fund_type")
  private AccountTypeMap fundType = null;

  @SerializedName("time")
  private Long time = null;

  @SerializedName("deposit")
  private Long deposit = null;

  @SerializedName("paid")
  private Long paid = null;

  @SerializedName("trans_in")
  private Long transIn = null;

  @SerializedName("trans_out")
  private Long transOut = null;

  @SerializedName("credit_modify")
  private Long creditModify = null;

  @SerializedName("balance")
  private Long balance = null;

  @SerializedName("preauth_balance")
  private Long preauthBalance = null;

  @SerializedName("preauth_out_pay")
  private Long preauthOutPay = null;

  @SerializedName("preauth_in_refund")
  private Long preauthInRefund = null;

  @SerializedName("acct_out_pay")
  private Long acctOutPay = null;

  @SerializedName("acct_out_pay_share")
  private Long acctOutPayShare = null;

  @SerializedName("share_out_pay")
  private Long shareOutPay = null;

  public DailyBalanceReportGetListStruct accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public DailyBalanceReportGetListStruct fundType(AccountTypeMap fundType) {
    this.fundType = fundType;
    return this;
  }

  /**
   * Get fundType
   *
   * @return fundType
   */
  @ApiModelProperty(value = "")
  public AccountTypeMap getFundType() {
    return fundType;
  }

  public void setFundType(AccountTypeMap fundType) {
    this.fundType = fundType;
  }

  public DailyBalanceReportGetListStruct time(Long time) {
    this.time = time;
    return this;
  }

  /**
   * Get time
   *
   * @return time
   */
  @ApiModelProperty(value = "")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public DailyBalanceReportGetListStruct deposit(Long deposit) {
    this.deposit = deposit;
    return this;
  }

  /**
   * Get deposit
   *
   * @return deposit
   */
  @ApiModelProperty(value = "")
  public Long getDeposit() {
    return deposit;
  }

  public void setDeposit(Long deposit) {
    this.deposit = deposit;
  }

  public DailyBalanceReportGetListStruct paid(Long paid) {
    this.paid = paid;
    return this;
  }

  /**
   * Get paid
   *
   * @return paid
   */
  @ApiModelProperty(value = "")
  public Long getPaid() {
    return paid;
  }

  public void setPaid(Long paid) {
    this.paid = paid;
  }

  public DailyBalanceReportGetListStruct transIn(Long transIn) {
    this.transIn = transIn;
    return this;
  }

  /**
   * Get transIn
   *
   * @return transIn
   */
  @ApiModelProperty(value = "")
  public Long getTransIn() {
    return transIn;
  }

  public void setTransIn(Long transIn) {
    this.transIn = transIn;
  }

  public DailyBalanceReportGetListStruct transOut(Long transOut) {
    this.transOut = transOut;
    return this;
  }

  /**
   * Get transOut
   *
   * @return transOut
   */
  @ApiModelProperty(value = "")
  public Long getTransOut() {
    return transOut;
  }

  public void setTransOut(Long transOut) {
    this.transOut = transOut;
  }

  public DailyBalanceReportGetListStruct creditModify(Long creditModify) {
    this.creditModify = creditModify;
    return this;
  }

  /**
   * Get creditModify
   *
   * @return creditModify
   */
  @ApiModelProperty(value = "")
  public Long getCreditModify() {
    return creditModify;
  }

  public void setCreditModify(Long creditModify) {
    this.creditModify = creditModify;
  }

  public DailyBalanceReportGetListStruct balance(Long balance) {
    this.balance = balance;
    return this;
  }

  /**
   * Get balance
   *
   * @return balance
   */
  @ApiModelProperty(value = "")
  public Long getBalance() {
    return balance;
  }

  public void setBalance(Long balance) {
    this.balance = balance;
  }

  public DailyBalanceReportGetListStruct preauthBalance(Long preauthBalance) {
    this.preauthBalance = preauthBalance;
    return this;
  }

  /**
   * Get preauthBalance
   *
   * @return preauthBalance
   */
  @ApiModelProperty(value = "")
  public Long getPreauthBalance() {
    return preauthBalance;
  }

  public void setPreauthBalance(Long preauthBalance) {
    this.preauthBalance = preauthBalance;
  }

  public DailyBalanceReportGetListStruct preauthOutPay(Long preauthOutPay) {
    this.preauthOutPay = preauthOutPay;
    return this;
  }

  /**
   * Get preauthOutPay
   *
   * @return preauthOutPay
   */
  @ApiModelProperty(value = "")
  public Long getPreauthOutPay() {
    return preauthOutPay;
  }

  public void setPreauthOutPay(Long preauthOutPay) {
    this.preauthOutPay = preauthOutPay;
  }

  public DailyBalanceReportGetListStruct preauthInRefund(Long preauthInRefund) {
    this.preauthInRefund = preauthInRefund;
    return this;
  }

  /**
   * Get preauthInRefund
   *
   * @return preauthInRefund
   */
  @ApiModelProperty(value = "")
  public Long getPreauthInRefund() {
    return preauthInRefund;
  }

  public void setPreauthInRefund(Long preauthInRefund) {
    this.preauthInRefund = preauthInRefund;
  }

  public DailyBalanceReportGetListStruct acctOutPay(Long acctOutPay) {
    this.acctOutPay = acctOutPay;
    return this;
  }

  /**
   * Get acctOutPay
   *
   * @return acctOutPay
   */
  @ApiModelProperty(value = "")
  public Long getAcctOutPay() {
    return acctOutPay;
  }

  public void setAcctOutPay(Long acctOutPay) {
    this.acctOutPay = acctOutPay;
  }

  public DailyBalanceReportGetListStruct acctOutPayShare(Long acctOutPayShare) {
    this.acctOutPayShare = acctOutPayShare;
    return this;
  }

  /**
   * Get acctOutPayShare
   *
   * @return acctOutPayShare
   */
  @ApiModelProperty(value = "")
  public Long getAcctOutPayShare() {
    return acctOutPayShare;
  }

  public void setAcctOutPayShare(Long acctOutPayShare) {
    this.acctOutPayShare = acctOutPayShare;
  }

  public DailyBalanceReportGetListStruct shareOutPay(Long shareOutPay) {
    this.shareOutPay = shareOutPay;
    return this;
  }

  /**
   * Get shareOutPay
   *
   * @return shareOutPay
   */
  @ApiModelProperty(value = "")
  public Long getShareOutPay() {
    return shareOutPay;
  }

  public void setShareOutPay(Long shareOutPay) {
    this.shareOutPay = shareOutPay;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DailyBalanceReportGetListStruct dailyBalanceReportGetListStruct =
        (DailyBalanceReportGetListStruct) o;
    return Objects.equals(this.accountId, dailyBalanceReportGetListStruct.accountId)
        && Objects.equals(this.fundType, dailyBalanceReportGetListStruct.fundType)
        && Objects.equals(this.time, dailyBalanceReportGetListStruct.time)
        && Objects.equals(this.deposit, dailyBalanceReportGetListStruct.deposit)
        && Objects.equals(this.paid, dailyBalanceReportGetListStruct.paid)
        && Objects.equals(this.transIn, dailyBalanceReportGetListStruct.transIn)
        && Objects.equals(this.transOut, dailyBalanceReportGetListStruct.transOut)
        && Objects.equals(this.creditModify, dailyBalanceReportGetListStruct.creditModify)
        && Objects.equals(this.balance, dailyBalanceReportGetListStruct.balance)
        && Objects.equals(this.preauthBalance, dailyBalanceReportGetListStruct.preauthBalance)
        && Objects.equals(this.preauthOutPay, dailyBalanceReportGetListStruct.preauthOutPay)
        && Objects.equals(this.preauthInRefund, dailyBalanceReportGetListStruct.preauthInRefund)
        && Objects.equals(this.acctOutPay, dailyBalanceReportGetListStruct.acctOutPay)
        && Objects.equals(this.acctOutPayShare, dailyBalanceReportGetListStruct.acctOutPayShare)
        && Objects.equals(this.shareOutPay, dailyBalanceReportGetListStruct.shareOutPay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountId,
        fundType,
        time,
        deposit,
        paid,
        transIn,
        transOut,
        creditModify,
        balance,
        preauthBalance,
        preauthOutPay,
        preauthInRefund,
        acctOutPay,
        acctOutPayShare,
        shareOutPay);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
