/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 动态内容广告属性 */
@ApiModel(description = "动态内容广告属性")
public class DcaSpec {
  @SerializedName("recommend_method_ids")
  private List<Long> recommendMethodIds = null;

  @SerializedName("set_id")
  private String setId = null;

  public DcaSpec recommendMethodIds(List<Long> recommendMethodIds) {
    this.recommendMethodIds = recommendMethodIds;
    return this;
  }

  public DcaSpec addRecommendMethodIdsItem(Long recommendMethodIdsItem) {
    if (this.recommendMethodIds == null) {
      this.recommendMethodIds = new ArrayList<Long>();
    }
    this.recommendMethodIds.add(recommendMethodIdsItem);
    return this;
  }

  /**
   * Get recommendMethodIds
   *
   * @return recommendMethodIds
   */
  @ApiModelProperty(value = "")
  public List<Long> getRecommendMethodIds() {
    return recommendMethodIds;
  }

  public void setRecommendMethodIds(List<Long> recommendMethodIds) {
    this.recommendMethodIds = recommendMethodIds;
  }

  public DcaSpec setId(String setId) {
    this.setId = setId;
    return this;
  }

  /**
   * Get setId
   *
   * @return setId
   */
  @ApiModelProperty(value = "")
  public String getSetId() {
    return setId;
  }

  public void setSetId(String setId) {
    this.setId = setId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DcaSpec dcaSpec = (DcaSpec) o;
    return Objects.equals(this.recommendMethodIds, dcaSpec.recommendMethodIds)
        && Objects.equals(this.setId, dcaSpec.setId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recommendMethodIds, setId);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
