/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** dc状态列表 */
@ApiModel(description = "dc状态列表")
public class DcInfoStruct {
  @SerializedName("status_extra_text")
  private String statusExtraText = null;

  @SerializedName("dynamic_creative_retry_status")
  private DynamicCreativeRetryStatus dynamicCreativeRetryStatus = null;

  public DcInfoStruct statusExtraText(String statusExtraText) {
    this.statusExtraText = statusExtraText;
    return this;
  }

  /**
   * Get statusExtraText
   *
   * @return statusExtraText
   */
  @ApiModelProperty(value = "")
  public String getStatusExtraText() {
    return statusExtraText;
  }

  public void setStatusExtraText(String statusExtraText) {
    this.statusExtraText = statusExtraText;
  }

  public DcInfoStruct dynamicCreativeRetryStatus(
      DynamicCreativeRetryStatus dynamicCreativeRetryStatus) {
    this.dynamicCreativeRetryStatus = dynamicCreativeRetryStatus;
    return this;
  }

  /**
   * Get dynamicCreativeRetryStatus
   *
   * @return dynamicCreativeRetryStatus
   */
  @ApiModelProperty(value = "")
  public DynamicCreativeRetryStatus getDynamicCreativeRetryStatus() {
    return dynamicCreativeRetryStatus;
  }

  public void setDynamicCreativeRetryStatus(DynamicCreativeRetryStatus dynamicCreativeRetryStatus) {
    this.dynamicCreativeRetryStatus = dynamicCreativeRetryStatus;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DcInfoStruct dcInfoStruct = (DcInfoStruct) o;
    return Objects.equals(this.statusExtraText, dcInfoStruct.statusExtraText)
        && Objects.equals(this.dynamicCreativeRetryStatus, dcInfoStruct.dynamicCreativeRetryStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusExtraText, dynamicCreativeRetryStatus);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
