/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** DynamicAdVideoGetResponseData */
public class DynamicAdVideoGetResponseData {
  @SerializedName("video_id")
  private String videoId = null;

  @SerializedName("video_preview_image_url")
  private String videoPreviewImageUrl = null;

  @SerializedName("video_preview_image_id")
  private Long videoPreviewImageId = null;

  public DynamicAdVideoGetResponseData videoId(String videoId) {
    this.videoId = videoId;
    return this;
  }

  /**
   * Get videoId
   *
   * @return videoId
   */
  @ApiModelProperty(value = "")
  public String getVideoId() {
    return videoId;
  }

  public void setVideoId(String videoId) {
    this.videoId = videoId;
  }

  public DynamicAdVideoGetResponseData videoPreviewImageUrl(String videoPreviewImageUrl) {
    this.videoPreviewImageUrl = videoPreviewImageUrl;
    return this;
  }

  /**
   * Get videoPreviewImageUrl
   *
   * @return videoPreviewImageUrl
   */
  @ApiModelProperty(value = "")
  public String getVideoPreviewImageUrl() {
    return videoPreviewImageUrl;
  }

  public void setVideoPreviewImageUrl(String videoPreviewImageUrl) {
    this.videoPreviewImageUrl = videoPreviewImageUrl;
  }

  public DynamicAdVideoGetResponseData videoPreviewImageId(Long videoPreviewImageId) {
    this.videoPreviewImageId = videoPreviewImageId;
    return this;
  }

  /**
   * Get videoPreviewImageId
   *
   * @return videoPreviewImageId
   */
  @ApiModelProperty(value = "")
  public Long getVideoPreviewImageId() {
    return videoPreviewImageId;
  }

  public void setVideoPreviewImageId(Long videoPreviewImageId) {
    this.videoPreviewImageId = videoPreviewImageId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DynamicAdVideoGetResponseData dynamicAdVideoGetResponseData = (DynamicAdVideoGetResponseData) o;
    return Objects.equals(this.videoId, dynamicAdVideoGetResponseData.videoId)
        && Objects.equals(
            this.videoPreviewImageUrl, dynamicAdVideoGetResponseData.videoPreviewImageUrl)
        && Objects.equals(
            this.videoPreviewImageId, dynamicAdVideoGetResponseData.videoPreviewImageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(videoId, videoPreviewImageUrl, videoPreviewImageId);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
