/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 图片组件元素 */
@ApiModel(description = "图片组件元素")
public class ElementImage {
  @SerializedName("image_id")
  private List<String> imageId = null;

  public ElementImage imageId(List<String> imageId) {
    this.imageId = imageId;
    return this;
  }

  public ElementImage addImageIdItem(String imageIdItem) {
    if (this.imageId == null) {
      this.imageId = new ArrayList<String>();
    }
    this.imageId.add(imageIdItem);
    return this;
  }

  /**
   * Get imageId
   *
   * @return imageId
   */
  @ApiModelProperty(value = "")
  public List<String> getImageId() {
    return imageId;
  }

  public void setImageId(List<String> imageId) {
    this.imageId = imageId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementImage elementImage = (ElementImage) o;
    return Objects.equals(this.imageId, elementImage.imageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageId);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
