/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 预审结果实体 */
@ApiModel(description = "预审结果实体")
public class ElementPrereviewStruct {
  @SerializedName("element_type")
  private PreReviewElementType elementType = null;

  @SerializedName("element_content")
  private String elementContent = null;

  @SerializedName("risk_level")
  private RiskLevel riskLevel = null;

  @SerializedName("pre_review_details")
  private List<PreReviewDetailStruct> preReviewDetails = null;

  public ElementPrereviewStruct elementType(PreReviewElementType elementType) {
    this.elementType = elementType;
    return this;
  }

  /**
   * Get elementType
   *
   * @return elementType
   */
  @ApiModelProperty(value = "")
  public PreReviewElementType getElementType() {
    return elementType;
  }

  public void setElementType(PreReviewElementType elementType) {
    this.elementType = elementType;
  }

  public ElementPrereviewStruct elementContent(String elementContent) {
    this.elementContent = elementContent;
    return this;
  }

  /**
   * Get elementContent
   *
   * @return elementContent
   */
  @ApiModelProperty(value = "")
  public String getElementContent() {
    return elementContent;
  }

  public void setElementContent(String elementContent) {
    this.elementContent = elementContent;
  }

  public ElementPrereviewStruct riskLevel(RiskLevel riskLevel) {
    this.riskLevel = riskLevel;
    return this;
  }

  /**
   * Get riskLevel
   *
   * @return riskLevel
   */
  @ApiModelProperty(value = "")
  public RiskLevel getRiskLevel() {
    return riskLevel;
  }

  public void setRiskLevel(RiskLevel riskLevel) {
    this.riskLevel = riskLevel;
  }

  public ElementPrereviewStruct preReviewDetails(List<PreReviewDetailStruct> preReviewDetails) {
    this.preReviewDetails = preReviewDetails;
    return this;
  }

  public ElementPrereviewStruct addPreReviewDetailsItem(
      PreReviewDetailStruct preReviewDetailsItem) {
    if (this.preReviewDetails == null) {
      this.preReviewDetails = new ArrayList<PreReviewDetailStruct>();
    }
    this.preReviewDetails.add(preReviewDetailsItem);
    return this;
  }

  /**
   * Get preReviewDetails
   *
   * @return preReviewDetails
   */
  @ApiModelProperty(value = "")
  public List<PreReviewDetailStruct> getPreReviewDetails() {
    return preReviewDetails;
  }

  public void setPreReviewDetails(List<PreReviewDetailStruct> preReviewDetails) {
    this.preReviewDetails = preReviewDetails;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementPrereviewStruct elementPrereviewStruct = (ElementPrereviewStruct) o;
    return Objects.equals(this.elementType, elementPrereviewStruct.elementType)
        && Objects.equals(this.elementContent, elementPrereviewStruct.elementContent)
        && Objects.equals(this.riskLevel, elementPrereviewStruct.riskLevel)
        && Objects.equals(this.preReviewDetails, elementPrereviewStruct.preReviewDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elementType, elementContent, riskLevel, preReviewDetails);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
