/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;


import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 评论状态 */
@JsonAdapter(FinderCommentFlag.Adapter.class)
public enum FinderCommentFlag {
  GENERAL("General"),

  SELECTION("Selection");

  private String value;

  FinderCommentFlag(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FinderCommentFlag fromValue(String text) {
    for (FinderCommentFlag b : FinderCommentFlag.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<FinderCommentFlag> {
    @Override
    public void write(final JsonWriter jsonWriter, final FinderCommentFlag enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FinderCommentFlag read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FinderCommentFlag.fromValue(String.valueOf(value));
    }
  }
}
