/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 返回结构 */
@ApiModel(description = "返回结构")
public class FinderAdObjectListGetListStruct {
  @SerializedName("finder_ad_object_id")
  private Long finderAdObjectId = null;

  @SerializedName("finder_object")
  private FinderObjectStruct finderObject = null;

  @SerializedName("dynamic_creative_id")
  private Long dynamicCreativeId = null;

  public FinderAdObjectListGetListStruct finderAdObjectId(Long finderAdObjectId) {
    this.finderAdObjectId = finderAdObjectId;
    return this;
  }

  /**
   * Get finderAdObjectId
   *
   * @return finderAdObjectId
   */
  @ApiModelProperty(value = "")
  public Long getFinderAdObjectId() {
    return finderAdObjectId;
  }

  public void setFinderAdObjectId(Long finderAdObjectId) {
    this.finderAdObjectId = finderAdObjectId;
  }

  public FinderAdObjectListGetListStruct finderObject(FinderObjectStruct finderObject) {
    this.finderObject = finderObject;
    return this;
  }

  /**
   * Get finderObject
   *
   * @return finderObject
   */
  @ApiModelProperty(value = "")
  public FinderObjectStruct getFinderObject() {
    return finderObject;
  }

  public void setFinderObject(FinderObjectStruct finderObject) {
    this.finderObject = finderObject;
  }

  public FinderAdObjectListGetListStruct dynamicCreativeId(Long dynamicCreativeId) {
    this.dynamicCreativeId = dynamicCreativeId;
    return this;
  }

  /**
   * Get dynamicCreativeId
   *
   * @return dynamicCreativeId
   */
  @ApiModelProperty(value = "")
  public Long getDynamicCreativeId() {
    return dynamicCreativeId;
  }

  public void setDynamicCreativeId(Long dynamicCreativeId) {
    this.dynamicCreativeId = dynamicCreativeId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinderAdObjectListGetListStruct finderAdObjectListGetListStruct =
        (FinderAdObjectListGetListStruct) o;
    return Objects.equals(this.finderAdObjectId, finderAdObjectListGetListStruct.finderAdObjectId)
        && Objects.equals(this.finderObject, finderAdObjectListGetListStruct.finderObject)
        && Objects.equals(
            this.dynamicCreativeId, finderAdObjectListGetListStruct.dynamicCreativeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(finderAdObjectId, finderObject, dynamicCreativeId);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
