/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** GetWxGameAppGiftPackGetRequest */
public class GetWxGameAppGiftPackGetRequest {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("appid")
  private String appid = null;

  public GetWxGameAppGiftPackGetRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public GetWxGameAppGiftPackGetRequest appid(String appid) {
    this.appid = appid;
    return this;
  }

  /**
   * Get appid
   *
   * @return appid
   */
  @ApiModelProperty(value = "")
  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetWxGameAppGiftPackGetRequest getWxGameAppGiftPackGetRequest =
        (GetWxGameAppGiftPackGetRequest) o;
    return Objects.equals(this.accountId, getWxGameAppGiftPackGetRequest.accountId)
        && Objects.equals(this.appid, getWxGameAppGiftPackGetRequest.appid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, appid);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
