/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 关注公众号组件元素 */
@ApiModel(description = "关注公众号组件元素")
public class GhSpec {
  @SerializedName("fast_follow")
  private Long fastFollow = null;

  @SerializedName("btn_title")
  private String btnTitle = null;

  @SerializedName("font_color")
  private String fontColor = null;

  @SerializedName("btn_bg_color_theme")
  private String btnBgColorTheme = null;

  @SerializedName("btn_border_color_theme")
  private String btnBorderColorTheme = null;

  @SerializedName("btn_font_type")
  private Long btnFontType = null;

  @SerializedName("padding_top")
  private Long paddingTop = null;

  @SerializedName("padding_bottom")
  private Long paddingBottom = null;

  @SerializedName("use_icon")
  private Long useIcon = null;

  public GhSpec fastFollow(Long fastFollow) {
    this.fastFollow = fastFollow;
    return this;
  }

  /**
   * Get fastFollow
   *
   * @return fastFollow
   */
  @ApiModelProperty(value = "")
  public Long getFastFollow() {
    return fastFollow;
  }

  public void setFastFollow(Long fastFollow) {
    this.fastFollow = fastFollow;
  }

  public GhSpec btnTitle(String btnTitle) {
    this.btnTitle = btnTitle;
    return this;
  }

  /**
   * Get btnTitle
   *
   * @return btnTitle
   */
  @ApiModelProperty(value = "")
  public String getBtnTitle() {
    return btnTitle;
  }

  public void setBtnTitle(String btnTitle) {
    this.btnTitle = btnTitle;
  }

  public GhSpec fontColor(String fontColor) {
    this.fontColor = fontColor;
    return this;
  }

  /**
   * Get fontColor
   *
   * @return fontColor
   */
  @ApiModelProperty(value = "")
  public String getFontColor() {
    return fontColor;
  }

  public void setFontColor(String fontColor) {
    this.fontColor = fontColor;
  }

  public GhSpec btnBgColorTheme(String btnBgColorTheme) {
    this.btnBgColorTheme = btnBgColorTheme;
    return this;
  }

  /**
   * Get btnBgColorTheme
   *
   * @return btnBgColorTheme
   */
  @ApiModelProperty(value = "")
  public String getBtnBgColorTheme() {
    return btnBgColorTheme;
  }

  public void setBtnBgColorTheme(String btnBgColorTheme) {
    this.btnBgColorTheme = btnBgColorTheme;
  }

  public GhSpec btnBorderColorTheme(String btnBorderColorTheme) {
    this.btnBorderColorTheme = btnBorderColorTheme;
    return this;
  }

  /**
   * Get btnBorderColorTheme
   *
   * @return btnBorderColorTheme
   */
  @ApiModelProperty(value = "")
  public String getBtnBorderColorTheme() {
    return btnBorderColorTheme;
  }

  public void setBtnBorderColorTheme(String btnBorderColorTheme) {
    this.btnBorderColorTheme = btnBorderColorTheme;
  }

  public GhSpec btnFontType(Long btnFontType) {
    this.btnFontType = btnFontType;
    return this;
  }

  /**
   * Get btnFontType
   *
   * @return btnFontType
   */
  @ApiModelProperty(value = "")
  public Long getBtnFontType() {
    return btnFontType;
  }

  public void setBtnFontType(Long btnFontType) {
    this.btnFontType = btnFontType;
  }

  public GhSpec paddingTop(Long paddingTop) {
    this.paddingTop = paddingTop;
    return this;
  }

  /**
   * Get paddingTop
   *
   * @return paddingTop
   */
  @ApiModelProperty(value = "")
  public Long getPaddingTop() {
    return paddingTop;
  }

  public void setPaddingTop(Long paddingTop) {
    this.paddingTop = paddingTop;
  }

  public GhSpec paddingBottom(Long paddingBottom) {
    this.paddingBottom = paddingBottom;
    return this;
  }

  /**
   * Get paddingBottom
   *
   * @return paddingBottom
   */
  @ApiModelProperty(value = "")
  public Long getPaddingBottom() {
    return paddingBottom;
  }

  public void setPaddingBottom(Long paddingBottom) {
    this.paddingBottom = paddingBottom;
  }

  public GhSpec useIcon(Long useIcon) {
    this.useIcon = useIcon;
    return this;
  }

  /**
   * Get useIcon
   *
   * @return useIcon
   */
  @ApiModelProperty(value = "")
  public Long getUseIcon() {
    return useIcon;
  }

  public void setUseIcon(Long useIcon) {
    this.useIcon = useIcon;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GhSpec ghSpec = (GhSpec) o;
    return Objects.equals(this.fastFollow, ghSpec.fastFollow)
        && Objects.equals(this.btnTitle, ghSpec.btnTitle)
        && Objects.equals(this.fontColor, ghSpec.fontColor)
        && Objects.equals(this.btnBgColorTheme, ghSpec.btnBgColorTheme)
        && Objects.equals(this.btnBorderColorTheme, ghSpec.btnBorderColorTheme)
        && Objects.equals(this.btnFontType, ghSpec.btnFontType)
        && Objects.equals(this.paddingTop, ghSpec.paddingTop)
        && Objects.equals(this.paddingBottom, ghSpec.paddingBottom)
        && Objects.equals(this.useIcon, ghSpec.useIcon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        fastFollow,
        btnTitle,
        fontColor,
        btnBgColorTheme,
        btnBorderColorTheme,
        btnFontType,
        paddingTop,
        paddingBottom,
        useIcon);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
