/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 图片素材 */
@ApiModel(description = "图片素材")
public class ImageItem {
  @SerializedName("image_id")
  private Long imageId = null;

  @SerializedName("info")
  private List<ImageInfoItem> info = null;

  public ImageItem imageId(Long imageId) {
    this.imageId = imageId;
    return this;
  }

  /**
   * Get imageId
   *
   * @return imageId
   */
  @ApiModelProperty(value = "")
  public Long getImageId() {
    return imageId;
  }

  public void setImageId(Long imageId) {
    this.imageId = imageId;
  }

  public ImageItem info(List<ImageInfoItem> info) {
    this.info = info;
    return this;
  }

  public ImageItem addInfoItem(ImageInfoItem infoItem) {
    if (this.info == null) {
      this.info = new ArrayList<ImageInfoItem>();
    }
    this.info.add(infoItem);
    return this;
  }

  /**
   * Get info
   *
   * @return info
   */
  @ApiModelProperty(value = "")
  public List<ImageInfoItem> getInfo() {
    return info;
  }

  public void setInfo(List<ImageInfoItem> info) {
    this.info = info;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageItem imageItem = (ImageItem) o;
    return Objects.equals(this.imageId, imageItem.imageId)
        && Objects.equals(this.info, imageItem.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageId, info);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
