/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 配置信息要求说明 */
@ApiModel(description = "配置信息要求说明")
public class InfoStruct {
  @SerializedName("desc")
  private String desc = null;

  @SerializedName("width")
  private Long width = null;

  @SerializedName("height")
  private Long height = null;

  @SerializedName("max_length")
  private Long maxLength = null;

  @SerializedName("info_number_only")
  private Boolean infoNumberOnly = null;

  @SerializedName("max")
  private Long max = null;

  @SerializedName("min")
  private Long min = null;

  public InfoStruct desc(String desc) {
    this.desc = desc;
    return this;
  }

  /**
   * Get desc
   *
   * @return desc
   */
  @ApiModelProperty(value = "")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public InfoStruct width(Long width) {
    this.width = width;
    return this;
  }

  /**
   * Get width
   *
   * @return width
   */
  @ApiModelProperty(value = "")
  public Long getWidth() {
    return width;
  }

  public void setWidth(Long width) {
    this.width = width;
  }

  public InfoStruct height(Long height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   *
   * @return height
   */
  @ApiModelProperty(value = "")
  public Long getHeight() {
    return height;
  }

  public void setHeight(Long height) {
    this.height = height;
  }

  public InfoStruct maxLength(Long maxLength) {
    this.maxLength = maxLength;
    return this;
  }

  /**
   * Get maxLength
   *
   * @return maxLength
   */
  @ApiModelProperty(value = "")
  public Long getMaxLength() {
    return maxLength;
  }

  public void setMaxLength(Long maxLength) {
    this.maxLength = maxLength;
  }

  public InfoStruct infoNumberOnly(Boolean infoNumberOnly) {
    this.infoNumberOnly = infoNumberOnly;
    return this;
  }

  /**
   * Get infoNumberOnly
   *
   * @return infoNumberOnly
   */
  @ApiModelProperty(value = "")
  public Boolean isInfoNumberOnly() {
    return infoNumberOnly;
  }

  public void setInfoNumberOnly(Boolean infoNumberOnly) {
    this.infoNumberOnly = infoNumberOnly;
  }

  public InfoStruct max(Long max) {
    this.max = max;
    return this;
  }

  /**
   * Get max
   *
   * @return max
   */
  @ApiModelProperty(value = "")
  public Long getMax() {
    return max;
  }

  public void setMax(Long max) {
    this.max = max;
  }

  public InfoStruct min(Long min) {
    this.min = min;
    return this;
  }

  /**
   * Get min
   *
   * @return min
   */
  @ApiModelProperty(value = "")
  public Long getMin() {
    return min;
  }

  public void setMin(Long min) {
    this.min = min;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoStruct infoStruct = (InfoStruct) o;
    return Objects.equals(this.desc, infoStruct.desc)
        && Objects.equals(this.width, infoStruct.width)
        && Objects.equals(this.height, infoStruct.height)
        && Objects.equals(this.maxLength, infoStruct.maxLength)
        && Objects.equals(this.infoNumberOnly, infoStruct.infoNumberOnly)
        && Objects.equals(this.max, infoStruct.max)
        && Objects.equals(this.min, infoStruct.min);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desc, width, height, maxLength, infoNumberOnly, max, min);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
