/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 门店营业时间信息结构 */
@ApiModel(description = "门店营业时间信息结构")
public class OpeningHours {
  @SerializedName("time_series")
  private String timeSeries = null;

  @SerializedName("date")
  private LocalStorePeakPeriodDate date = null;

  public OpeningHours timeSeries(String timeSeries) {
    this.timeSeries = timeSeries;
    return this;
  }

  /**
   * Get timeSeries
   *
   * @return timeSeries
   */
  @ApiModelProperty(value = "")
  public String getTimeSeries() {
    return timeSeries;
  }

  public void setTimeSeries(String timeSeries) {
    this.timeSeries = timeSeries;
  }

  public OpeningHours date(LocalStorePeakPeriodDate date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   *
   * @return date
   */
  @ApiModelProperty(value = "")
  public LocalStorePeakPeriodDate getDate() {
    return date;
  }

  public void setDate(LocalStorePeakPeriodDate date) {
    this.date = date;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpeningHours openingHours = (OpeningHours) o;
    return Objects.equals(this.timeSeries, openingHours.timeSeries)
        && Objects.equals(this.date, openingHours.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeSeries, date);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
