/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** RtatargetBindGetResponseData */
public class RtatargetBindGetResponseData {
  @SerializedName("Total")
  private Long total = null;

  @SerializedName("Page")
  private Long page = null;

  @SerializedName("Size")
  private Long size = null;

  @SerializedName("Records")
  private List<RtaTargetBindListRecord> records = null;

  public RtatargetBindGetResponseData total(Long total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   *
   * @return total
   */
  @ApiModelProperty(value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public RtatargetBindGetResponseData page(Long page) {
    this.page = page;
    return this;
  }

  /**
   * Get page
   *
   * @return page
   */
  @ApiModelProperty(value = "")
  public Long getPage() {
    return page;
  }

  public void setPage(Long page) {
    this.page = page;
  }

  public RtatargetBindGetResponseData size(Long size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   *
   * @return size
   */
  @ApiModelProperty(value = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public RtatargetBindGetResponseData records(List<RtaTargetBindListRecord> records) {
    this.records = records;
    return this;
  }

  public RtatargetBindGetResponseData addRecordsItem(RtaTargetBindListRecord recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<RtaTargetBindListRecord>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * Get records
   *
   * @return records
   */
  @ApiModelProperty(value = "")
  public List<RtaTargetBindListRecord> getRecords() {
    return records;
  }

  public void setRecords(List<RtaTargetBindListRecord> records) {
    this.records = records;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RtatargetBindGetResponseData rtatargetBindGetResponseData = (RtatargetBindGetResponseData) o;
    return Objects.equals(this.total, rtatargetBindGetResponseData.total)
        && Objects.equals(this.page, rtatargetBindGetResponseData.page)
        && Objects.equals(this.size, rtatargetBindGetResponseData.size)
        && Objects.equals(this.records, rtatargetBindGetResponseData.records);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, page, size, records);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
