/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** RtatargetDeleteRequest */
public class RtatargetDeleteRequest {
  @SerializedName("data")
  private List<RtaTargetDeleteObject> data = null;

  public RtatargetDeleteRequest data(List<RtaTargetDeleteObject> data) {
    this.data = data;
    return this;
  }

  public RtatargetDeleteRequest addDataItem(RtaTargetDeleteObject dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<RtaTargetDeleteObject>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   *
   * @return data
   */
  @ApiModelProperty(value = "")
  public List<RtaTargetDeleteObject> getData() {
    return data;
  }

  public void setData(List<RtaTargetDeleteObject> data) {
    this.data = data;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RtatargetDeleteRequest rtatargetDeleteRequest = (RtatargetDeleteRequest) o;
    return Objects.equals(this.data, rtatargetDeleteRequest.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
