/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** SearchDynamicCreativesAddRequest */
public class SearchDynamicCreativesAddRequest {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("adgroup_id")
  private Long adgroupId = null;

  @SerializedName("dynamic_creative_name")
  private String dynamicCreativeName = null;

  @SerializedName("creative_template_id")
  private Long creativeTemplateId = null;

  @SerializedName("delivery_mode")
  private DeliveryMode deliveryMode = null;

  @SerializedName("creative_components")
  private CreativeComponents creativeComponents = null;

  @SerializedName("search_intelligent_extension")
  private ModelSwitch searchIntelligentExtension = null;

  @SerializedName("sublink_switch")
  private AdvertiserSublinkSwitch sublinkSwitch = null;

  @SerializedName("pic_material_switch")
  private AdvertiserPicMaterialSwitch picMaterialSwitch = null;

  public SearchDynamicCreativesAddRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public SearchDynamicCreativesAddRequest adgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
    return this;
  }

  /**
   * Get adgroupId
   *
   * @return adgroupId
   */
  @ApiModelProperty(value = "")
  public Long getAdgroupId() {
    return adgroupId;
  }

  public void setAdgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
  }

  public SearchDynamicCreativesAddRequest dynamicCreativeName(String dynamicCreativeName) {
    this.dynamicCreativeName = dynamicCreativeName;
    return this;
  }

  /**
   * Get dynamicCreativeName
   *
   * @return dynamicCreativeName
   */
  @ApiModelProperty(value = "")
  public String getDynamicCreativeName() {
    return dynamicCreativeName;
  }

  public void setDynamicCreativeName(String dynamicCreativeName) {
    this.dynamicCreativeName = dynamicCreativeName;
  }

  public SearchDynamicCreativesAddRequest creativeTemplateId(Long creativeTemplateId) {
    this.creativeTemplateId = creativeTemplateId;
    return this;
  }

  /**
   * Get creativeTemplateId
   *
   * @return creativeTemplateId
   */
  @ApiModelProperty(value = "")
  public Long getCreativeTemplateId() {
    return creativeTemplateId;
  }

  public void setCreativeTemplateId(Long creativeTemplateId) {
    this.creativeTemplateId = creativeTemplateId;
  }

  public SearchDynamicCreativesAddRequest deliveryMode(DeliveryMode deliveryMode) {
    this.deliveryMode = deliveryMode;
    return this;
  }

  /**
   * Get deliveryMode
   *
   * @return deliveryMode
   */
  @ApiModelProperty(value = "")
  public DeliveryMode getDeliveryMode() {
    return deliveryMode;
  }

  public void setDeliveryMode(DeliveryMode deliveryMode) {
    this.deliveryMode = deliveryMode;
  }

  public SearchDynamicCreativesAddRequest creativeComponents(
      CreativeComponents creativeComponents) {
    this.creativeComponents = creativeComponents;
    return this;
  }

  /**
   * Get creativeComponents
   *
   * @return creativeComponents
   */
  @ApiModelProperty(value = "")
  public CreativeComponents getCreativeComponents() {
    return creativeComponents;
  }

  public void setCreativeComponents(CreativeComponents creativeComponents) {
    this.creativeComponents = creativeComponents;
  }

  public SearchDynamicCreativesAddRequest searchIntelligentExtension(
      ModelSwitch searchIntelligentExtension) {
    this.searchIntelligentExtension = searchIntelligentExtension;
    return this;
  }

  /**
   * Get searchIntelligentExtension
   *
   * @return searchIntelligentExtension
   */
  @ApiModelProperty(value = "")
  public ModelSwitch getSearchIntelligentExtension() {
    return searchIntelligentExtension;
  }

  public void setSearchIntelligentExtension(ModelSwitch searchIntelligentExtension) {
    this.searchIntelligentExtension = searchIntelligentExtension;
  }

  public SearchDynamicCreativesAddRequest sublinkSwitch(AdvertiserSublinkSwitch sublinkSwitch) {
    this.sublinkSwitch = sublinkSwitch;
    return this;
  }

  /**
   * Get sublinkSwitch
   *
   * @return sublinkSwitch
   */
  @ApiModelProperty(value = "")
  public AdvertiserSublinkSwitch getSublinkSwitch() {
    return sublinkSwitch;
  }

  public void setSublinkSwitch(AdvertiserSublinkSwitch sublinkSwitch) {
    this.sublinkSwitch = sublinkSwitch;
  }

  public SearchDynamicCreativesAddRequest picMaterialSwitch(
      AdvertiserPicMaterialSwitch picMaterialSwitch) {
    this.picMaterialSwitch = picMaterialSwitch;
    return this;
  }

  /**
   * Get picMaterialSwitch
   *
   * @return picMaterialSwitch
   */
  @ApiModelProperty(value = "")
  public AdvertiserPicMaterialSwitch getPicMaterialSwitch() {
    return picMaterialSwitch;
  }

  public void setPicMaterialSwitch(AdvertiserPicMaterialSwitch picMaterialSwitch) {
    this.picMaterialSwitch = picMaterialSwitch;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchDynamicCreativesAddRequest searchDynamicCreativesAddRequest =
        (SearchDynamicCreativesAddRequest) o;
    return Objects.equals(this.accountId, searchDynamicCreativesAddRequest.accountId)
        && Objects.equals(this.adgroupId, searchDynamicCreativesAddRequest.adgroupId)
        && Objects.equals(
            this.dynamicCreativeName, searchDynamicCreativesAddRequest.dynamicCreativeName)
        && Objects.equals(
            this.creativeTemplateId, searchDynamicCreativesAddRequest.creativeTemplateId)
        && Objects.equals(this.deliveryMode, searchDynamicCreativesAddRequest.deliveryMode)
        && Objects.equals(
            this.creativeComponents, searchDynamicCreativesAddRequest.creativeComponents)
        && Objects.equals(
            this.searchIntelligentExtension,
            searchDynamicCreativesAddRequest.searchIntelligentExtension)
        && Objects.equals(this.sublinkSwitch, searchDynamicCreativesAddRequest.sublinkSwitch)
        && Objects.equals(
            this.picMaterialSwitch, searchDynamicCreativesAddRequest.picMaterialSwitch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountId,
        adgroupId,
        dynamicCreativeName,
        creativeTemplateId,
        deliveryMode,
        creativeComponents,
        searchIntelligentExtension,
        sublinkSwitch,
        picMaterialSwitch);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
