/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 卖点图组件 */
@ApiModel(description = "卖点图组件")
public class ShopImageStruct {
  @SerializedName("shop_image_switch")
  private Boolean shopImageSwitch = null;

  @SerializedName("dynamic_shop_image_switch")
  private Boolean dynamicShopImageSwitch = null;

  @SerializedName("shop_image_id")
  private String shopImageId = null;

  @SerializedName("shop_image_title")
  private String shopImageTitle = null;

  @SerializedName("shop_image_description")
  private String shopImageDescription = null;

  public ShopImageStruct shopImageSwitch(Boolean shopImageSwitch) {
    this.shopImageSwitch = shopImageSwitch;
    return this;
  }

  /**
   * Get shopImageSwitch
   *
   * @return shopImageSwitch
   */
  @ApiModelProperty(value = "")
  public Boolean isShopImageSwitch() {
    return shopImageSwitch;
  }

  public void setShopImageSwitch(Boolean shopImageSwitch) {
    this.shopImageSwitch = shopImageSwitch;
  }

  public ShopImageStruct dynamicShopImageSwitch(Boolean dynamicShopImageSwitch) {
    this.dynamicShopImageSwitch = dynamicShopImageSwitch;
    return this;
  }

  /**
   * Get dynamicShopImageSwitch
   *
   * @return dynamicShopImageSwitch
   */
  @ApiModelProperty(value = "")
  public Boolean isDynamicShopImageSwitch() {
    return dynamicShopImageSwitch;
  }

  public void setDynamicShopImageSwitch(Boolean dynamicShopImageSwitch) {
    this.dynamicShopImageSwitch = dynamicShopImageSwitch;
  }

  public ShopImageStruct shopImageId(String shopImageId) {
    this.shopImageId = shopImageId;
    return this;
  }

  /**
   * Get shopImageId
   *
   * @return shopImageId
   */
  @ApiModelProperty(value = "")
  public String getShopImageId() {
    return shopImageId;
  }

  public void setShopImageId(String shopImageId) {
    this.shopImageId = shopImageId;
  }

  public ShopImageStruct shopImageTitle(String shopImageTitle) {
    this.shopImageTitle = shopImageTitle;
    return this;
  }

  /**
   * Get shopImageTitle
   *
   * @return shopImageTitle
   */
  @ApiModelProperty(value = "")
  public String getShopImageTitle() {
    return shopImageTitle;
  }

  public void setShopImageTitle(String shopImageTitle) {
    this.shopImageTitle = shopImageTitle;
  }

  public ShopImageStruct shopImageDescription(String shopImageDescription) {
    this.shopImageDescription = shopImageDescription;
    return this;
  }

  /**
   * Get shopImageDescription
   *
   * @return shopImageDescription
   */
  @ApiModelProperty(value = "")
  public String getShopImageDescription() {
    return shopImageDescription;
  }

  public void setShopImageDescription(String shopImageDescription) {
    this.shopImageDescription = shopImageDescription;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopImageStruct shopImageStruct = (ShopImageStruct) o;
    return Objects.equals(this.shopImageSwitch, shopImageStruct.shopImageSwitch)
        && Objects.equals(this.dynamicShopImageSwitch, shopImageStruct.dynamicShopImageSwitch)
        && Objects.equals(this.shopImageId, shopImageStruct.shopImageId)
        && Objects.equals(this.shopImageTitle, shopImageStruct.shopImageTitle)
        && Objects.equals(this.shopImageDescription, shopImageStruct.shopImageDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        shopImageSwitch, dynamicShopImageSwitch, shopImageId, shopImageTitle, shopImageDescription);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
