/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 首日变现目标信息 */
@ApiModel(description = "首日变现目标信息")
public class SmartDeliveryGoalFirstDayMonetizationSpec {
  @SerializedName("first_day_monetization_roi")
  private Double firstDayMonetizationRoi = null;

  public SmartDeliveryGoalFirstDayMonetizationSpec firstDayMonetizationRoi(
      Double firstDayMonetizationRoi) {
    this.firstDayMonetizationRoi = firstDayMonetizationRoi;
    return this;
  }

  /**
   * Get firstDayMonetizationRoi
   *
   * @return firstDayMonetizationRoi
   */
  @ApiModelProperty(value = "")
  public Double getFirstDayMonetizationRoi() {
    return firstDayMonetizationRoi;
  }

  public void setFirstDayMonetizationRoi(Double firstDayMonetizationRoi) {
    this.firstDayMonetizationRoi = firstDayMonetizationRoi;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmartDeliveryGoalFirstDayMonetizationSpec smartDeliveryGoalFirstDayMonetizationSpec =
        (SmartDeliveryGoalFirstDayMonetizationSpec) o;
    return Objects.equals(
        this.firstDayMonetizationRoi,
        smartDeliveryGoalFirstDayMonetizationSpec.firstDayMonetizationRoi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstDayMonetizationRoi);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
