/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 返回结构 */
@ApiModel(description = "返回结构")
public class WalletBasicInfoGetWalletInfo {
  @SerializedName("agency_id")
  private Long agencyId = null;

  @SerializedName("agency_name")
  private String agencyName = null;

  @SerializedName("wallet_id")
  private Long walletId = null;

  @SerializedName("wallet_name")
  private String walletName = null;

  @SerializedName("mdm_id")
  private Long mdmId = null;

  @SerializedName("mdm_name")
  private String mdmName = null;

  @SerializedName("balance")
  private Long balance = null;

  @SerializedName("bind_advertiser_cnt")
  private Long bindAdvertiserCnt = null;

  @SerializedName("binding_account_list")
  private List<Long> bindingAccountList = null;

  @SerializedName("tag_list")
  private List<String> tagList = null;

  @SerializedName("balance_info_list")
  private List<WalletListBalanceStruct> balanceInfoList = null;

  @SerializedName("contact_info_list")
  private List<ContactInfoStruct> contactInfoList = null;

  @SerializedName("contact_notify_condition")
  private ContactNotifyCondition contactNotifyCondition = null;

  public WalletBasicInfoGetWalletInfo agencyId(Long agencyId) {
    this.agencyId = agencyId;
    return this;
  }

  /**
   * Get agencyId
   *
   * @return agencyId
   */
  @ApiModelProperty(value = "")
  public Long getAgencyId() {
    return agencyId;
  }

  public void setAgencyId(Long agencyId) {
    this.agencyId = agencyId;
  }

  public WalletBasicInfoGetWalletInfo agencyName(String agencyName) {
    this.agencyName = agencyName;
    return this;
  }

  /**
   * Get agencyName
   *
   * @return agencyName
   */
  @ApiModelProperty(value = "")
  public String getAgencyName() {
    return agencyName;
  }

  public void setAgencyName(String agencyName) {
    this.agencyName = agencyName;
  }

  public WalletBasicInfoGetWalletInfo walletId(Long walletId) {
    this.walletId = walletId;
    return this;
  }

  /**
   * Get walletId
   *
   * @return walletId
   */
  @ApiModelProperty(value = "")
  public Long getWalletId() {
    return walletId;
  }

  public void setWalletId(Long walletId) {
    this.walletId = walletId;
  }

  public WalletBasicInfoGetWalletInfo walletName(String walletName) {
    this.walletName = walletName;
    return this;
  }

  /**
   * Get walletName
   *
   * @return walletName
   */
  @ApiModelProperty(value = "")
  public String getWalletName() {
    return walletName;
  }

  public void setWalletName(String walletName) {
    this.walletName = walletName;
  }

  public WalletBasicInfoGetWalletInfo mdmId(Long mdmId) {
    this.mdmId = mdmId;
    return this;
  }

  /**
   * Get mdmId
   *
   * @return mdmId
   */
  @ApiModelProperty(value = "")
  public Long getMdmId() {
    return mdmId;
  }

  public void setMdmId(Long mdmId) {
    this.mdmId = mdmId;
  }

  public WalletBasicInfoGetWalletInfo mdmName(String mdmName) {
    this.mdmName = mdmName;
    return this;
  }

  /**
   * Get mdmName
   *
   * @return mdmName
   */
  @ApiModelProperty(value = "")
  public String getMdmName() {
    return mdmName;
  }

  public void setMdmName(String mdmName) {
    this.mdmName = mdmName;
  }

  public WalletBasicInfoGetWalletInfo balance(Long balance) {
    this.balance = balance;
    return this;
  }

  /**
   * Get balance
   *
   * @return balance
   */
  @ApiModelProperty(value = "")
  public Long getBalance() {
    return balance;
  }

  public void setBalance(Long balance) {
    this.balance = balance;
  }

  public WalletBasicInfoGetWalletInfo bindAdvertiserCnt(Long bindAdvertiserCnt) {
    this.bindAdvertiserCnt = bindAdvertiserCnt;
    return this;
  }

  /**
   * Get bindAdvertiserCnt
   *
   * @return bindAdvertiserCnt
   */
  @ApiModelProperty(value = "")
  public Long getBindAdvertiserCnt() {
    return bindAdvertiserCnt;
  }

  public void setBindAdvertiserCnt(Long bindAdvertiserCnt) {
    this.bindAdvertiserCnt = bindAdvertiserCnt;
  }

  public WalletBasicInfoGetWalletInfo bindingAccountList(List<Long> bindingAccountList) {
    this.bindingAccountList = bindingAccountList;
    return this;
  }

  public WalletBasicInfoGetWalletInfo addBindingAccountListItem(Long bindingAccountListItem) {
    if (this.bindingAccountList == null) {
      this.bindingAccountList = new ArrayList<Long>();
    }
    this.bindingAccountList.add(bindingAccountListItem);
    return this;
  }

  /**
   * Get bindingAccountList
   *
   * @return bindingAccountList
   */
  @ApiModelProperty(value = "")
  public List<Long> getBindingAccountList() {
    return bindingAccountList;
  }

  public void setBindingAccountList(List<Long> bindingAccountList) {
    this.bindingAccountList = bindingAccountList;
  }

  public WalletBasicInfoGetWalletInfo tagList(List<String> tagList) {
    this.tagList = tagList;
    return this;
  }

  public WalletBasicInfoGetWalletInfo addTagListItem(String tagListItem) {
    if (this.tagList == null) {
      this.tagList = new ArrayList<String>();
    }
    this.tagList.add(tagListItem);
    return this;
  }

  /**
   * Get tagList
   *
   * @return tagList
   */
  @ApiModelProperty(value = "")
  public List<String> getTagList() {
    return tagList;
  }

  public void setTagList(List<String> tagList) {
    this.tagList = tagList;
  }

  public WalletBasicInfoGetWalletInfo balanceInfoList(
      List<WalletListBalanceStruct> balanceInfoList) {
    this.balanceInfoList = balanceInfoList;
    return this;
  }

  public WalletBasicInfoGetWalletInfo addBalanceInfoListItem(
      WalletListBalanceStruct balanceInfoListItem) {
    if (this.balanceInfoList == null) {
      this.balanceInfoList = new ArrayList<WalletListBalanceStruct>();
    }
    this.balanceInfoList.add(balanceInfoListItem);
    return this;
  }

  /**
   * Get balanceInfoList
   *
   * @return balanceInfoList
   */
  @ApiModelProperty(value = "")
  public List<WalletListBalanceStruct> getBalanceInfoList() {
    return balanceInfoList;
  }

  public void setBalanceInfoList(List<WalletListBalanceStruct> balanceInfoList) {
    this.balanceInfoList = balanceInfoList;
  }

  public WalletBasicInfoGetWalletInfo contactInfoList(List<ContactInfoStruct> contactInfoList) {
    this.contactInfoList = contactInfoList;
    return this;
  }

  public WalletBasicInfoGetWalletInfo addContactInfoListItem(
      ContactInfoStruct contactInfoListItem) {
    if (this.contactInfoList == null) {
      this.contactInfoList = new ArrayList<ContactInfoStruct>();
    }
    this.contactInfoList.add(contactInfoListItem);
    return this;
  }

  /**
   * Get contactInfoList
   *
   * @return contactInfoList
   */
  @ApiModelProperty(value = "")
  public List<ContactInfoStruct> getContactInfoList() {
    return contactInfoList;
  }

  public void setContactInfoList(List<ContactInfoStruct> contactInfoList) {
    this.contactInfoList = contactInfoList;
  }

  public WalletBasicInfoGetWalletInfo contactNotifyCondition(
      ContactNotifyCondition contactNotifyCondition) {
    this.contactNotifyCondition = contactNotifyCondition;
    return this;
  }

  /**
   * Get contactNotifyCondition
   *
   * @return contactNotifyCondition
   */
  @ApiModelProperty(value = "")
  public ContactNotifyCondition getContactNotifyCondition() {
    return contactNotifyCondition;
  }

  public void setContactNotifyCondition(ContactNotifyCondition contactNotifyCondition) {
    this.contactNotifyCondition = contactNotifyCondition;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletBasicInfoGetWalletInfo walletBasicInfoGetWalletInfo = (WalletBasicInfoGetWalletInfo) o;
    return Objects.equals(this.agencyId, walletBasicInfoGetWalletInfo.agencyId)
        && Objects.equals(this.agencyName, walletBasicInfoGetWalletInfo.agencyName)
        && Objects.equals(this.walletId, walletBasicInfoGetWalletInfo.walletId)
        && Objects.equals(this.walletName, walletBasicInfoGetWalletInfo.walletName)
        && Objects.equals(this.mdmId, walletBasicInfoGetWalletInfo.mdmId)
        && Objects.equals(this.mdmName, walletBasicInfoGetWalletInfo.mdmName)
        && Objects.equals(this.balance, walletBasicInfoGetWalletInfo.balance)
        && Objects.equals(this.bindAdvertiserCnt, walletBasicInfoGetWalletInfo.bindAdvertiserCnt)
        && Objects.equals(this.bindingAccountList, walletBasicInfoGetWalletInfo.bindingAccountList)
        && Objects.equals(this.tagList, walletBasicInfoGetWalletInfo.tagList)
        && Objects.equals(this.balanceInfoList, walletBasicInfoGetWalletInfo.balanceInfoList)
        && Objects.equals(this.contactInfoList, walletBasicInfoGetWalletInfo.contactInfoList)
        && Objects.equals(
            this.contactNotifyCondition, walletBasicInfoGetWalletInfo.contactNotifyCondition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        agencyId,
        agencyName,
        walletId,
        walletName,
        mdmId,
        mdmName,
        balance,
        bindAdvertiserCnt,
        bindingAccountList,
        tagList,
        balanceInfoList,
        contactInfoList,
        contactNotifyCondition);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
