/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** WatermarksAddRequest */
public class WatermarksAddRequest {
  @SerializedName("account_id")
  private Long accountId = null;

  @SerializedName("organization_id")
  private Long organizationId = null;

  @SerializedName("source_type")
  private ParamSourceType sourceType = null;

  @SerializedName("materials")
  private List<EachMaterialItemStruct> materials = null;

  @SerializedName("material_type")
  private WatermarkMaterialType materialType = null;

  @SerializedName("watermark_configs")
  private List<WatermarkConfigStruct> watermarkConfigs = null;

  public WatermarksAddRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   *
   * @return accountId
   */
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public WatermarksAddRequest organizationId(Long organizationId) {
    this.organizationId = organizationId;
    return this;
  }

  /**
   * Get organizationId
   *
   * @return organizationId
   */
  @ApiModelProperty(value = "")
  public Long getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Long organizationId) {
    this.organizationId = organizationId;
  }

  public WatermarksAddRequest sourceType(ParamSourceType sourceType) {
    this.sourceType = sourceType;
    return this;
  }

  /**
   * Get sourceType
   *
   * @return sourceType
   */
  @ApiModelProperty(value = "")
  public ParamSourceType getSourceType() {
    return sourceType;
  }

  public void setSourceType(ParamSourceType sourceType) {
    this.sourceType = sourceType;
  }

  public WatermarksAddRequest materials(List<EachMaterialItemStruct> materials) {
    this.materials = materials;
    return this;
  }

  public WatermarksAddRequest addMaterialsItem(EachMaterialItemStruct materialsItem) {
    if (this.materials == null) {
      this.materials = new ArrayList<EachMaterialItemStruct>();
    }
    this.materials.add(materialsItem);
    return this;
  }

  /**
   * Get materials
   *
   * @return materials
   */
  @ApiModelProperty(value = "")
  public List<EachMaterialItemStruct> getMaterials() {
    return materials;
  }

  public void setMaterials(List<EachMaterialItemStruct> materials) {
    this.materials = materials;
  }

  public WatermarksAddRequest materialType(WatermarkMaterialType materialType) {
    this.materialType = materialType;
    return this;
  }

  /**
   * Get materialType
   *
   * @return materialType
   */
  @ApiModelProperty(value = "")
  public WatermarkMaterialType getMaterialType() {
    return materialType;
  }

  public void setMaterialType(WatermarkMaterialType materialType) {
    this.materialType = materialType;
  }

  public WatermarksAddRequest watermarkConfigs(List<WatermarkConfigStruct> watermarkConfigs) {
    this.watermarkConfigs = watermarkConfigs;
    return this;
  }

  public WatermarksAddRequest addWatermarkConfigsItem(WatermarkConfigStruct watermarkConfigsItem) {
    if (this.watermarkConfigs == null) {
      this.watermarkConfigs = new ArrayList<WatermarkConfigStruct>();
    }
    this.watermarkConfigs.add(watermarkConfigsItem);
    return this;
  }

  /**
   * Get watermarkConfigs
   *
   * @return watermarkConfigs
   */
  @ApiModelProperty(value = "")
  public List<WatermarkConfigStruct> getWatermarkConfigs() {
    return watermarkConfigs;
  }

  public void setWatermarkConfigs(List<WatermarkConfigStruct> watermarkConfigs) {
    this.watermarkConfigs = watermarkConfigs;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WatermarksAddRequest watermarksAddRequest = (WatermarksAddRequest) o;
    return Objects.equals(this.accountId, watermarksAddRequest.accountId)
        && Objects.equals(this.organizationId, watermarksAddRequest.organizationId)
        && Objects.equals(this.sourceType, watermarksAddRequest.sourceType)
        && Objects.equals(this.materials, watermarksAddRequest.materials)
        && Objects.equals(this.materialType, watermarksAddRequest.materialType)
        && Objects.equals(this.watermarkConfigs, watermarksAddRequest.watermarkConfigs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountId, organizationId, sourceType, materials, materialType, watermarkConfigs);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
