/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model.v3;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 返回结构 */
@ApiModel(description = "返回结构")
public class WechatStoreProductItemsGetListStruct {
  @SerializedName("product_outer_id")
  private String productOuterId = null;

  @SerializedName("product_name")
  private String productName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("product_primary_image_urls")
  private List<String> productPrimaryImageUrls = null;

  @SerializedName("product_detail_image_urls")
  private List<String> productDetailImageUrls = null;

  @SerializedName("price")
  private Double price = null;

  @SerializedName("first_category_id")
  private Long firstCategoryId = null;

  @SerializedName("first_category_name")
  private String firstCategoryName = null;

  @SerializedName("second_category_id")
  private Long secondCategoryId = null;

  @SerializedName("second_category_name")
  private String secondCategoryName = null;

  @SerializedName("third_category_id")
  private Long thirdCategoryId = null;

  @SerializedName("third_category_name")
  private String thirdCategoryName = null;

  @SerializedName("fourth_category_id")
  private Long fourthCategoryId = null;

  @SerializedName("fourth_category_name")
  private String fourthCategoryName = null;

  @SerializedName("brand_name")
  private String brandName = null;

  @SerializedName("sales_volume")
  private Long salesVolume = null;

  @SerializedName("comment_num")
  private Long commentNum = null;

  @SerializedName("spu_link_status")
  private SpuLinkStatus spuLinkStatus = null;

  @SerializedName("link_spu_id")
  private String linkSpuId = null;

  @SerializedName("link_spu_name")
  private String linkSpuName = null;

  @SerializedName("wechat_store_product_status")
  private Long wechatStoreProductStatus = null;

  @SerializedName("wechat_store_product_ad_status")
  private Long wechatStoreProductAdStatus = null;

  @SerializedName("wechat_store_product_ad_unavailable_cause")
  private List<String> wechatStoreProductAdUnavailableCause = null;

  @SerializedName("store_price_item_list")
  private List<StorePriceItem> storePriceItemList = null;

  public WechatStoreProductItemsGetListStruct productOuterId(String productOuterId) {
    this.productOuterId = productOuterId;
    return this;
  }

  /**
   * Get productOuterId
   *
   * @return productOuterId
   */
  @ApiModelProperty(value = "")
  public String getProductOuterId() {
    return productOuterId;
  }

  public void setProductOuterId(String productOuterId) {
    this.productOuterId = productOuterId;
  }

  public WechatStoreProductItemsGetListStruct productName(String productName) {
    this.productName = productName;
    return this;
  }

  /**
   * Get productName
   *
   * @return productName
   */
  @ApiModelProperty(value = "")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public WechatStoreProductItemsGetListStruct description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   *
   * @return description
   */
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public WechatStoreProductItemsGetListStruct productPrimaryImageUrls(
      List<String> productPrimaryImageUrls) {
    this.productPrimaryImageUrls = productPrimaryImageUrls;
    return this;
  }

  public WechatStoreProductItemsGetListStruct addProductPrimaryImageUrlsItem(
      String productPrimaryImageUrlsItem) {
    if (this.productPrimaryImageUrls == null) {
      this.productPrimaryImageUrls = new ArrayList<String>();
    }
    this.productPrimaryImageUrls.add(productPrimaryImageUrlsItem);
    return this;
  }

  /**
   * Get productPrimaryImageUrls
   *
   * @return productPrimaryImageUrls
   */
  @ApiModelProperty(value = "")
  public List<String> getProductPrimaryImageUrls() {
    return productPrimaryImageUrls;
  }

  public void setProductPrimaryImageUrls(List<String> productPrimaryImageUrls) {
    this.productPrimaryImageUrls = productPrimaryImageUrls;
  }

  public WechatStoreProductItemsGetListStruct productDetailImageUrls(
      List<String> productDetailImageUrls) {
    this.productDetailImageUrls = productDetailImageUrls;
    return this;
  }

  public WechatStoreProductItemsGetListStruct addProductDetailImageUrlsItem(
      String productDetailImageUrlsItem) {
    if (this.productDetailImageUrls == null) {
      this.productDetailImageUrls = new ArrayList<String>();
    }
    this.productDetailImageUrls.add(productDetailImageUrlsItem);
    return this;
  }

  /**
   * Get productDetailImageUrls
   *
   * @return productDetailImageUrls
   */
  @ApiModelProperty(value = "")
  public List<String> getProductDetailImageUrls() {
    return productDetailImageUrls;
  }

  public void setProductDetailImageUrls(List<String> productDetailImageUrls) {
    this.productDetailImageUrls = productDetailImageUrls;
  }

  public WechatStoreProductItemsGetListStruct price(Double price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   *
   * @return price
   */
  @ApiModelProperty(value = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public WechatStoreProductItemsGetListStruct firstCategoryId(Long firstCategoryId) {
    this.firstCategoryId = firstCategoryId;
    return this;
  }

  /**
   * Get firstCategoryId
   *
   * @return firstCategoryId
   */
  @ApiModelProperty(value = "")
  public Long getFirstCategoryId() {
    return firstCategoryId;
  }

  public void setFirstCategoryId(Long firstCategoryId) {
    this.firstCategoryId = firstCategoryId;
  }

  public WechatStoreProductItemsGetListStruct firstCategoryName(String firstCategoryName) {
    this.firstCategoryName = firstCategoryName;
    return this;
  }

  /**
   * Get firstCategoryName
   *
   * @return firstCategoryName
   */
  @ApiModelProperty(value = "")
  public String getFirstCategoryName() {
    return firstCategoryName;
  }

  public void setFirstCategoryName(String firstCategoryName) {
    this.firstCategoryName = firstCategoryName;
  }

  public WechatStoreProductItemsGetListStruct secondCategoryId(Long secondCategoryId) {
    this.secondCategoryId = secondCategoryId;
    return this;
  }

  /**
   * Get secondCategoryId
   *
   * @return secondCategoryId
   */
  @ApiModelProperty(value = "")
  public Long getSecondCategoryId() {
    return secondCategoryId;
  }

  public void setSecondCategoryId(Long secondCategoryId) {
    this.secondCategoryId = secondCategoryId;
  }

  public WechatStoreProductItemsGetListStruct secondCategoryName(String secondCategoryName) {
    this.secondCategoryName = secondCategoryName;
    return this;
  }

  /**
   * Get secondCategoryName
   *
   * @return secondCategoryName
   */
  @ApiModelProperty(value = "")
  public String getSecondCategoryName() {
    return secondCategoryName;
  }

  public void setSecondCategoryName(String secondCategoryName) {
    this.secondCategoryName = secondCategoryName;
  }

  public WechatStoreProductItemsGetListStruct thirdCategoryId(Long thirdCategoryId) {
    this.thirdCategoryId = thirdCategoryId;
    return this;
  }

  /**
   * Get thirdCategoryId
   *
   * @return thirdCategoryId
   */
  @ApiModelProperty(value = "")
  public Long getThirdCategoryId() {
    return thirdCategoryId;
  }

  public void setThirdCategoryId(Long thirdCategoryId) {
    this.thirdCategoryId = thirdCategoryId;
  }

  public WechatStoreProductItemsGetListStruct thirdCategoryName(String thirdCategoryName) {
    this.thirdCategoryName = thirdCategoryName;
    return this;
  }

  /**
   * Get thirdCategoryName
   *
   * @return thirdCategoryName
   */
  @ApiModelProperty(value = "")
  public String getThirdCategoryName() {
    return thirdCategoryName;
  }

  public void setThirdCategoryName(String thirdCategoryName) {
    this.thirdCategoryName = thirdCategoryName;
  }

  public WechatStoreProductItemsGetListStruct fourthCategoryId(Long fourthCategoryId) {
    this.fourthCategoryId = fourthCategoryId;
    return this;
  }

  /**
   * Get fourthCategoryId
   *
   * @return fourthCategoryId
   */
  @ApiModelProperty(value = "")
  public Long getFourthCategoryId() {
    return fourthCategoryId;
  }

  public void setFourthCategoryId(Long fourthCategoryId) {
    this.fourthCategoryId = fourthCategoryId;
  }

  public WechatStoreProductItemsGetListStruct fourthCategoryName(String fourthCategoryName) {
    this.fourthCategoryName = fourthCategoryName;
    return this;
  }

  /**
   * Get fourthCategoryName
   *
   * @return fourthCategoryName
   */
  @ApiModelProperty(value = "")
  public String getFourthCategoryName() {
    return fourthCategoryName;
  }

  public void setFourthCategoryName(String fourthCategoryName) {
    this.fourthCategoryName = fourthCategoryName;
  }

  public WechatStoreProductItemsGetListStruct brandName(String brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Get brandName
   *
   * @return brandName
   */
  @ApiModelProperty(value = "")
  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }

  public WechatStoreProductItemsGetListStruct salesVolume(Long salesVolume) {
    this.salesVolume = salesVolume;
    return this;
  }

  /**
   * Get salesVolume
   *
   * @return salesVolume
   */
  @ApiModelProperty(value = "")
  public Long getSalesVolume() {
    return salesVolume;
  }

  public void setSalesVolume(Long salesVolume) {
    this.salesVolume = salesVolume;
  }

  public WechatStoreProductItemsGetListStruct commentNum(Long commentNum) {
    this.commentNum = commentNum;
    return this;
  }

  /**
   * Get commentNum
   *
   * @return commentNum
   */
  @ApiModelProperty(value = "")
  public Long getCommentNum() {
    return commentNum;
  }

  public void setCommentNum(Long commentNum) {
    this.commentNum = commentNum;
  }

  public WechatStoreProductItemsGetListStruct spuLinkStatus(SpuLinkStatus spuLinkStatus) {
    this.spuLinkStatus = spuLinkStatus;
    return this;
  }

  /**
   * Get spuLinkStatus
   *
   * @return spuLinkStatus
   */
  @ApiModelProperty(value = "")
  public SpuLinkStatus getSpuLinkStatus() {
    return spuLinkStatus;
  }

  public void setSpuLinkStatus(SpuLinkStatus spuLinkStatus) {
    this.spuLinkStatus = spuLinkStatus;
  }

  public WechatStoreProductItemsGetListStruct linkSpuId(String linkSpuId) {
    this.linkSpuId = linkSpuId;
    return this;
  }

  /**
   * Get linkSpuId
   *
   * @return linkSpuId
   */
  @ApiModelProperty(value = "")
  public String getLinkSpuId() {
    return linkSpuId;
  }

  public void setLinkSpuId(String linkSpuId) {
    this.linkSpuId = linkSpuId;
  }

  public WechatStoreProductItemsGetListStruct linkSpuName(String linkSpuName) {
    this.linkSpuName = linkSpuName;
    return this;
  }

  /**
   * Get linkSpuName
   *
   * @return linkSpuName
   */
  @ApiModelProperty(value = "")
  public String getLinkSpuName() {
    return linkSpuName;
  }

  public void setLinkSpuName(String linkSpuName) {
    this.linkSpuName = linkSpuName;
  }

  public WechatStoreProductItemsGetListStruct wechatStoreProductStatus(
      Long wechatStoreProductStatus) {
    this.wechatStoreProductStatus = wechatStoreProductStatus;
    return this;
  }

  /**
   * Get wechatStoreProductStatus
   *
   * @return wechatStoreProductStatus
   */
  @ApiModelProperty(value = "")
  public Long getWechatStoreProductStatus() {
    return wechatStoreProductStatus;
  }

  public void setWechatStoreProductStatus(Long wechatStoreProductStatus) {
    this.wechatStoreProductStatus = wechatStoreProductStatus;
  }

  public WechatStoreProductItemsGetListStruct wechatStoreProductAdStatus(
      Long wechatStoreProductAdStatus) {
    this.wechatStoreProductAdStatus = wechatStoreProductAdStatus;
    return this;
  }

  /**
   * Get wechatStoreProductAdStatus
   *
   * @return wechatStoreProductAdStatus
   */
  @ApiModelProperty(value = "")
  public Long getWechatStoreProductAdStatus() {
    return wechatStoreProductAdStatus;
  }

  public void setWechatStoreProductAdStatus(Long wechatStoreProductAdStatus) {
    this.wechatStoreProductAdStatus = wechatStoreProductAdStatus;
  }

  public WechatStoreProductItemsGetListStruct wechatStoreProductAdUnavailableCause(
      List<String> wechatStoreProductAdUnavailableCause) {
    this.wechatStoreProductAdUnavailableCause = wechatStoreProductAdUnavailableCause;
    return this;
  }

  public WechatStoreProductItemsGetListStruct addWechatStoreProductAdUnavailableCauseItem(
      String wechatStoreProductAdUnavailableCauseItem) {
    if (this.wechatStoreProductAdUnavailableCause == null) {
      this.wechatStoreProductAdUnavailableCause = new ArrayList<String>();
    }
    this.wechatStoreProductAdUnavailableCause.add(wechatStoreProductAdUnavailableCauseItem);
    return this;
  }

  /**
   * Get wechatStoreProductAdUnavailableCause
   *
   * @return wechatStoreProductAdUnavailableCause
   */
  @ApiModelProperty(value = "")
  public List<String> getWechatStoreProductAdUnavailableCause() {
    return wechatStoreProductAdUnavailableCause;
  }

  public void setWechatStoreProductAdUnavailableCause(
      List<String> wechatStoreProductAdUnavailableCause) {
    this.wechatStoreProductAdUnavailableCause = wechatStoreProductAdUnavailableCause;
  }

  public WechatStoreProductItemsGetListStruct storePriceItemList(
      List<StorePriceItem> storePriceItemList) {
    this.storePriceItemList = storePriceItemList;
    return this;
  }

  public WechatStoreProductItemsGetListStruct addStorePriceItemListItem(
      StorePriceItem storePriceItemListItem) {
    if (this.storePriceItemList == null) {
      this.storePriceItemList = new ArrayList<StorePriceItem>();
    }
    this.storePriceItemList.add(storePriceItemListItem);
    return this;
  }

  /**
   * Get storePriceItemList
   *
   * @return storePriceItemList
   */
  @ApiModelProperty(value = "")
  public List<StorePriceItem> getStorePriceItemList() {
    return storePriceItemList;
  }

  public void setStorePriceItemList(List<StorePriceItem> storePriceItemList) {
    this.storePriceItemList = storePriceItemList;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WechatStoreProductItemsGetListStruct wechatStoreProductItemsGetListStruct =
        (WechatStoreProductItemsGetListStruct) o;
    return Objects.equals(this.productOuterId, wechatStoreProductItemsGetListStruct.productOuterId)
        && Objects.equals(this.productName, wechatStoreProductItemsGetListStruct.productName)
        && Objects.equals(this.description, wechatStoreProductItemsGetListStruct.description)
        && Objects.equals(
            this.productPrimaryImageUrls,
            wechatStoreProductItemsGetListStruct.productPrimaryImageUrls)
        && Objects.equals(
            this.productDetailImageUrls,
            wechatStoreProductItemsGetListStruct.productDetailImageUrls)
        && Objects.equals(this.price, wechatStoreProductItemsGetListStruct.price)
        && Objects.equals(
            this.firstCategoryId, wechatStoreProductItemsGetListStruct.firstCategoryId)
        && Objects.equals(
            this.firstCategoryName, wechatStoreProductItemsGetListStruct.firstCategoryName)
        && Objects.equals(
            this.secondCategoryId, wechatStoreProductItemsGetListStruct.secondCategoryId)
        && Objects.equals(
            this.secondCategoryName, wechatStoreProductItemsGetListStruct.secondCategoryName)
        && Objects.equals(
            this.thirdCategoryId, wechatStoreProductItemsGetListStruct.thirdCategoryId)
        && Objects.equals(
            this.thirdCategoryName, wechatStoreProductItemsGetListStruct.thirdCategoryName)
        && Objects.equals(
            this.fourthCategoryId, wechatStoreProductItemsGetListStruct.fourthCategoryId)
        && Objects.equals(
            this.fourthCategoryName, wechatStoreProductItemsGetListStruct.fourthCategoryName)
        && Objects.equals(this.brandName, wechatStoreProductItemsGetListStruct.brandName)
        && Objects.equals(this.salesVolume, wechatStoreProductItemsGetListStruct.salesVolume)
        && Objects.equals(this.commentNum, wechatStoreProductItemsGetListStruct.commentNum)
        && Objects.equals(this.spuLinkStatus, wechatStoreProductItemsGetListStruct.spuLinkStatus)
        && Objects.equals(this.linkSpuId, wechatStoreProductItemsGetListStruct.linkSpuId)
        && Objects.equals(this.linkSpuName, wechatStoreProductItemsGetListStruct.linkSpuName)
        && Objects.equals(
            this.wechatStoreProductStatus,
            wechatStoreProductItemsGetListStruct.wechatStoreProductStatus)
        && Objects.equals(
            this.wechatStoreProductAdStatus,
            wechatStoreProductItemsGetListStruct.wechatStoreProductAdStatus)
        && Objects.equals(
            this.wechatStoreProductAdUnavailableCause,
            wechatStoreProductItemsGetListStruct.wechatStoreProductAdUnavailableCause)
        && Objects.equals(
            this.storePriceItemList, wechatStoreProductItemsGetListStruct.storePriceItemList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        productOuterId,
        productName,
        description,
        productPrimaryImageUrls,
        productDetailImageUrls,
        price,
        firstCategoryId,
        firstCategoryName,
        secondCategoryId,
        secondCategoryName,
        thirdCategoryId,
        thirdCategoryName,
        fourthCategoryId,
        fourthCategoryName,
        brandName,
        salesVolume,
        commentNum,
        spuLinkStatus,
        linkSpuId,
        linkSpuName,
        wechatStoreProductStatus,
        wechatStoreProductAdStatus,
        wechatStoreProductAdUnavailableCause,
        storePriceItemList);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
