/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.container.v3;

import com.google.inject.Inject;
import com.tencent.ads.ApiContainer;
import com.tencent.ads.ApiException;
import com.tencent.ads.Pair;
import com.tencent.ads.anno.*;
import com.tencent.ads.api.v3.EstimationApi;
import com.tencent.ads.exception.TencentAdsResponseException;
import com.tencent.ads.model.v3.EstimationGetRequest;
import com.tencent.ads.model.v3.EstimationGetResponse;
import com.tencent.ads.model.v3.EstimationGetResponseData;

public class EstimationApiContainer extends ApiContainer {

  @Inject EstimationApi api;

  /**
   * 预估覆盖人数
   *
   * @param data (required)
   * @return EstimationGetResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   */
  public EstimationGetResponseData estimationGet(EstimationGetRequest data, Pair... headerPair)
      throws ApiException, TencentAdsResponseException {
    EstimationGetResponse resp = api.estimationGet(data, headerPair);
    handleResponse(gson.toJson(resp));
    return resp.getData();
  }
}
