/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.container.v3;

import com.google.inject.Inject;
import com.tencent.ads.ApiContainer;
import com.tencent.ads.ApiException;
import com.tencent.ads.anno.*;
import com.tencent.ads.api.v3.ProgrammedApi;
import com.tencent.ads.exception.TencentAdsResponseException;
import com.tencent.ads.model.v3.MaterialGroupCreateStruct;
import com.tencent.ads.model.v3.MaterialGroupUpdateStruct;
import com.tencent.ads.model.v3.ProgrammedAddResponse;
import com.tencent.ads.model.v3.ProgrammedAddResponseData;
import com.tencent.ads.model.v3.ProgrammedGetResponse;
import com.tencent.ads.model.v3.ProgrammedGetResponseData;
import com.tencent.ads.model.v3.ProgrammedUpdateResponse;
import com.tencent.ads.model.v3.ProgrammedUpdateResponseData;
import java.util.List;

public class ProgrammedApiContainer extends ApiContainer {

  @Inject ProgrammedApi api;

  /**
   * 创建模板预览接口
   *
   * @param accountId (required)
   * @param adgroupId (required)
   * @param createMaterialGroups (required)
   * @param autoDerivedProgramCreativeSwitch (optional)
   * @param standardSwitch (optional)
   * @param fields 返回参数的字段列表 (optional)
   * @return ProgrammedAddResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   */
  public ProgrammedAddResponseData programmedAdd(
      Long accountId,
      Long adgroupId,
      List<MaterialGroupCreateStruct> createMaterialGroups,
      Boolean autoDerivedProgramCreativeSwitch,
      Boolean standardSwitch,
      List<String> fields,
      String... headerPair)
      throws ApiException, TencentAdsResponseException {
    ProgrammedAddResponse resp =
        api.programmedAdd(
            accountId,
            adgroupId,
            createMaterialGroups,
            autoDerivedProgramCreativeSwitch,
            standardSwitch,
            fields,
            headerPair);
    handleResponse(gson.toJson(resp));
    return resp.getData();
  }

  /**
   * 获取模板预览接口
   *
   * @param accountId (required)
   * @param materialDeriveId (required)
   * @param fields 返回参数的字段列表 (optional)
   * @return ProgrammedGetResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   */
  public ProgrammedGetResponseData programmedGet(
      Long accountId, Long materialDeriveId, List<String> fields, String... headerPair)
      throws ApiException, TencentAdsResponseException {
    ProgrammedGetResponse resp = api.programmedGet(accountId, materialDeriveId, fields, headerPair);
    handleResponse(gson.toJson(resp));
    return resp.getData();
  }

  /**
   * 更新模板预览接口
   *
   * @param accountId (required)
   * @param materialDeriveId (required)
   * @param autoDerivedProgramCreativeSwitch (optional)
   * @param standardSwitch (optional)
   * @param updateMaterialGroups (optional)
   * @param fields 返回参数的字段列表 (optional)
   * @return ProgrammedUpdateResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   */
  public ProgrammedUpdateResponseData programmedUpdate(
      Long accountId,
      Long materialDeriveId,
      Boolean autoDerivedProgramCreativeSwitch,
      Boolean standardSwitch,
      List<MaterialGroupUpdateStruct> updateMaterialGroups,
      List<String> fields,
      String... headerPair)
      throws ApiException, TencentAdsResponseException {
    ProgrammedUpdateResponse resp =
        api.programmedUpdate(
            accountId,
            materialDeriveId,
            autoDerivedProgramCreativeSwitch,
            standardSwitch,
            updateMaterialGroups,
            fields,
            headerPair);
    handleResponse(gson.toJson(resp));
    return resp.getData();
  }
}
