/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.container.v3;

import com.google.inject.Inject;
import com.tencent.ads.ApiContainer;
import com.tencent.ads.ApiException;
import com.tencent.ads.Pair;
import com.tencent.ads.anno.*;
import com.tencent.ads.api.v3.PunishMetricsApi;
import com.tencent.ads.exception.TencentAdsResponseException;
import com.tencent.ads.model.v3.PunishMetricsGetRequest;
import com.tencent.ads.model.v3.PunishMetricsGetResponse;
import com.tencent.ads.model.v3.PunishMetricsGetResponseData;

public class PunishMetricsApiContainer extends ApiContainer {

  @Inject PunishMetricsApi api;

  /**
   * 获取处罚指标数据
   *
   * @param data (required)
   * @return PunishMetricsGetResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   */
  public PunishMetricsGetResponseData punishMetricsGet(
      PunishMetricsGetRequest data, Pair... headerPair)
      throws ApiException, TencentAdsResponseException {
    PunishMetricsGetResponse resp = api.punishMetricsGet(data, headerPair);
    handleResponse(gson.toJson(resp));
    return resp.getData();
  }
}
