/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tencent.ads.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * 小程序落地页，mini_program_id和mini_program_path要同时填写
 */
@ApiModel(description = "小程序落地页，mini_program_id和mini_program_path要同时填写")

public class AdcreativeMiniProgramSpec {

  @SerializedName("mini_program_id")
  private String miniProgramId = null;

  @SerializedName("mini_program_path")
  private String miniProgramPath = null;

  public AdcreativeMiniProgramSpec miniProgramId(String miniProgramId) {
    this.miniProgramId = miniProgramId;
    return this;
  }

  /**
   * Get miniProgramId
   *
   * @return miniProgramId
   **/
  @ApiModelProperty(value = "")
  public String getMiniProgramId() {
    return miniProgramId;
  }

  public void setMiniProgramId(String miniProgramId) {
    this.miniProgramId = miniProgramId;
  }

  public AdcreativeMiniProgramSpec miniProgramPath(String miniProgramPath) {
    this.miniProgramPath = miniProgramPath;
    return this;
  }

  /**
   * Get miniProgramPath
   *
   * @return miniProgramPath
   **/
  @ApiModelProperty(value = "")
  public String getMiniProgramPath() {
    return miniProgramPath;
  }

  public void setMiniProgramPath(String miniProgramPath) {
    this.miniProgramPath = miniProgramPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdcreativeMiniProgramSpec adcreativeMiniProgramSpec = (AdcreativeMiniProgramSpec) o;
    return Objects.equals(this.miniProgramId, adcreativeMiniProgramSpec.miniProgramId) &&
        Objects.equals(this.miniProgramPath, adcreativeMiniProgramSpec.miniProgramPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(miniProgramId, miniProgramPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdcreativeMiniProgramSpec {\n");

    sb.append("    miniProgramId: ").append(toIndentedString(miniProgramId)).append("\n");
    sb.append("    miniProgramPath: ").append(toIndentedString(miniProgramPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

