/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 广告行为类型 */
@JsonAdapter(AdRuleType.Adapter.class)
public enum AdRuleType {
  EXPOSURE("EXPOSURE"),

  CLICK("CLICK"),

  CONVERSION("CONVERSION");

  private String value;

  AdRuleType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AdRuleType fromValue(String text) {
    for (AdRuleType b : AdRuleType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AdRuleType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AdRuleType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AdRuleType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AdRuleType.fromValue(String.valueOf(value));
    }
  }
}
