/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 资产权限结构 */
@ApiModel(description = "资产权限结构")
public class AssetPermissionSpecStruct {
  @SerializedName("asset_permission_grant_type")
  private AssetPermissionGrantType assetPermissionGrantType = null;

  @SerializedName("asset_id")
  private Long assetId = null;

  public AssetPermissionSpecStruct assetPermissionGrantType(
      AssetPermissionGrantType assetPermissionGrantType) {
    this.assetPermissionGrantType = assetPermissionGrantType;
    return this;
  }

  /**
   * Get assetPermissionGrantType
   *
   * @return assetPermissionGrantType
   */
  @ApiModelProperty(value = "")
  public AssetPermissionGrantType getAssetPermissionGrantType() {
    return assetPermissionGrantType;
  }

  public void setAssetPermissionGrantType(AssetPermissionGrantType assetPermissionGrantType) {
    this.assetPermissionGrantType = assetPermissionGrantType;
  }

  public AssetPermissionSpecStruct assetId(Long assetId) {
    this.assetId = assetId;
    return this;
  }

  /**
   * Get assetId
   *
   * @return assetId
   */
  @ApiModelProperty(value = "")
  public Long getAssetId() {
    return assetId;
  }

  public void setAssetId(Long assetId) {
    this.assetId = assetId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetPermissionSpecStruct assetPermissionSpecStruct = (AssetPermissionSpecStruct) o;
    return Objects.equals(
            this.assetPermissionGrantType, assetPermissionSpecStruct.assetPermissionGrantType)
        && Objects.equals(this.assetId, assetPermissionSpecStruct.assetId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetPermissionGrantType, assetId);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
