/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;


import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 图文复合组件跳转方式，默认为btn_jump */
@JsonAdapter(CanvasImageTextJumpMode.Adapter.class)
public enum CanvasImageTextJumpMode {
  BTN_JUMP("btn_jump"),

  TOTAL_JUMP("total_jump");

  private String value;

  CanvasImageTextJumpMode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CanvasImageTextJumpMode fromValue(String text) {
    for (CanvasImageTextJumpMode b : CanvasImageTextJumpMode.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CanvasImageTextJumpMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final CanvasImageTextJumpMode enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CanvasImageTextJumpMode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CanvasImageTextJumpMode.fromValue(String.valueOf(value));
    }
  }
}
