/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;


import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 原生页类型 */
@JsonAdapter(CanvasType.Adapter.class)
public enum CanvasType {
  VIDEO("CANVAS_TYPE_VIDEO"),

  IMAGE("CANVAS_TYPE_IMAGE"),

  PORTRAIT_VIDEO("CANVAS_TYPE_PORTRAIT_VIDEO"),

  PORTRAIT_VIDEO_2("CANVAS_TYPE_PORTRAIT_VIDEO_2"),

  COMMON_PAGE("CANVAS_TYPE_COMMON_PAGE");

  private String value;

  CanvasType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CanvasType fromValue(String text) {
    for (CanvasType b : CanvasType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CanvasType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CanvasType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CanvasType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CanvasType.fromValue(String.valueOf(value));
    }
  }
}
