/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tencent.ads.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * 用户上传自定义特征文件规则
 */
@ApiModel(description = "用户上传自定义特征文件规则")

public class CustomFileFeatureSpec {

  @SerializedName("data_type")
  private FeatureValueDataType dataType = null;

  @SerializedName("is_multi_valued")
  private Boolean isMultiValued = null;

  @SerializedName("possible_values_size")
  private Long possibleValuesSize = null;

  public CustomFileFeatureSpec dataType(FeatureValueDataType dataType) {
    this.dataType = dataType;
    return this;
  }

  /**
   * Get dataType
   *
   * @return dataType
   **/
  @ApiModelProperty(value = "")
  public FeatureValueDataType getDataType() {
    return dataType;
  }

  public void setDataType(FeatureValueDataType dataType) {
    this.dataType = dataType;
  }

  public CustomFileFeatureSpec isMultiValued(Boolean isMultiValued) {
    this.isMultiValued = isMultiValued;
    return this;
  }

  /**
   * Get isMultiValued
   *
   * @return isMultiValued
   **/
  @ApiModelProperty(value = "")
  public Boolean isIsMultiValued() {
    return isMultiValued;
  }

  public void setIsMultiValued(Boolean isMultiValued) {
    this.isMultiValued = isMultiValued;
  }

  public CustomFileFeatureSpec possibleValuesSize(Long possibleValuesSize) {
    this.possibleValuesSize = possibleValuesSize;
    return this;
  }

  /**
   * Get possibleValuesSize
   *
   * @return possibleValuesSize
   **/
  @ApiModelProperty(value = "")
  public Long getPossibleValuesSize() {
    return possibleValuesSize;
  }

  public void setPossibleValuesSize(Long possibleValuesSize) {
    this.possibleValuesSize = possibleValuesSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFileFeatureSpec customFileFeatureSpec = (CustomFileFeatureSpec) o;
    return Objects.equals(this.dataType, customFileFeatureSpec.dataType) &&
        Objects.equals(this.isMultiValued, customFileFeatureSpec.isMultiValued) &&
        Objects.equals(this.possibleValuesSize, customFileFeatureSpec.possibleValuesSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataType, isMultiValued, possibleValuesSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFileFeatureSpec {\n");

    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    isMultiValued: ").append(toIndentedString(isMultiValued)).append("\n");
    sb.append("    possibleValuesSize: ").append(toIndentedString(possibleValuesSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

