/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;


import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 文件分发状态 */
@JsonAdapter(DnFileDispatchStatus.Adapter.class)
public enum DnFileDispatchStatus {
  UN_DISPATCHED("UN_DISPATCHED"),

  DISPATCHING("DISPATCHING"),

  DISPATCHED("DISPATCHED"),

  BE_CANCELLING("BE_CANCELLING");

  private String value;

  DnFileDispatchStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DnFileDispatchStatus fromValue(String text) {
    for (DnFileDispatchStatus b : DnFileDispatchStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DnFileDispatchStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final DnFileDispatchStatus enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DnFileDispatchStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DnFileDispatchStatus.fromValue(String.valueOf(value));
    }
  }
}
