/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;


import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 创意元素类型 */
@JsonAdapter(ElementType.Adapter.class)
public enum ElementType {
  TEXT("ELEMENT_TYPE_TEXT"),

  IMAGE("ELEMENT_TYPE_IMAGE"),

  VIDEO("ELEMENT_TYPE_VIDEO"),

  URL("ELEMENT_TYPE_URL"),

  ENUM("ELEMENT_TYPE_ENUM"),

  CANVAS("ELEMENT_TYPE_CANVAS"),

  STRUCT("ELEMENT_TYPE_STRUCT"),

  REFERENCE("ELEMENT_TYPE_REFERENCE"),

  BOOLEAN("ELEMENT_TYPE_BOOLEAN"),

  PHONE("ELEMENT_TYPE_PHONE"),

  FORM("ELEMENT_TYPE_FORM"),

  CONSULT("ELEMENT_TYPE_CONSULT"),

  NUMBER("ELEMENT_TYPE_NUMBER");

  private String value;

  ElementType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ElementType fromValue(String text) {
    for (ElementType b : ElementType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ElementType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ElementType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ElementType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ElementType.fromValue(String.valueOf(value));
    }
  }
}
