/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** LeadsCallVirtualNumberGetResponseData */
public class LeadsCallVirtualNumberGetResponseData {
  @SerializedName("virtual_number")
  private String virtualNumber = null;

  @SerializedName("request_id")
  private String requestId = null;

  @SerializedName("contact_id")
  private String contactId = null;

  public LeadsCallVirtualNumberGetResponseData virtualNumber(String virtualNumber) {
    this.virtualNumber = virtualNumber;
    return this;
  }

  /**
   * Get virtualNumber
   *
   * @return virtualNumber
   */
  @ApiModelProperty(value = "")
  public String getVirtualNumber() {
    return virtualNumber;
  }

  public void setVirtualNumber(String virtualNumber) {
    this.virtualNumber = virtualNumber;
  }

  public LeadsCallVirtualNumberGetResponseData requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   *
   * @return requestId
   */
  @ApiModelProperty(value = "")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public LeadsCallVirtualNumberGetResponseData contactId(String contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * Get contactId
   *
   * @return contactId
   */
  @ApiModelProperty(value = "")
  public String getContactId() {
    return contactId;
  }

  public void setContactId(String contactId) {
    this.contactId = contactId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeadsCallVirtualNumberGetResponseData leadsCallVirtualNumberGetResponseData =
        (LeadsCallVirtualNumberGetResponseData) o;
    return Objects.equals(this.virtualNumber, leadsCallVirtualNumberGetResponseData.virtualNumber)
        && Objects.equals(this.requestId, leadsCallVirtualNumberGetResponseData.requestId)
        && Objects.equals(this.contactId, leadsCallVirtualNumberGetResponseData.contactId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(virtualNumber, requestId, contactId);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
