/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 无效原因 */
@JsonAdapter(LeadCluesLeadsIneffectReason.Adapter.class)
public enum LeadCluesLeadsIneffectReason {
  EMPTY("LEADS_INEFFECT_REASON_EMPTY"),

  IDENTITY_MISMATCHED("LEADS_INEFFECT_REASON_IDENTITY_MISMATCHED"),

  REGION_MISMATCHED("LEADS_INEFFECT_REASON_REGION_MISMATCHED"),

  DATA_DUPLICATION("LEADS_INEFFECT_REASON_DATA_DUPLICATION"),

  TEL_NOT_CONNECTED("LEADS_INEFFECT_REASON_TEL_NOT_CONNECTED"),

  NO_INTENTION("LEADS_INEFFECT_REASON_NO_INTENTION"),

  UNKNOWN("LEADS_INEFFECT_REASON_UNKNOWN");

  private String value;

  LeadCluesLeadsIneffectReason(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LeadCluesLeadsIneffectReason fromValue(String text) {
    for (LeadCluesLeadsIneffectReason b : LeadCluesLeadsIneffectReason.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<LeadCluesLeadsIneffectReason> {
    @Override
    public void write(final JsonWriter jsonWriter, final LeadCluesLeadsIneffectReason enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LeadCluesLeadsIneffectReason read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LeadCluesLeadsIneffectReason.fromValue(String.valueOf(value));
    }
  }
}
