/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 创建页面返回数据结构 */
@ApiModel(description = "创建页面返回数据结构")
public class PageOperateResponses {
  @SerializedName("page_service_id")
  private String pageServiceId = null;

  @SerializedName("code")
  private Long code = null;

  @SerializedName("message")
  private String message = null;

  public PageOperateResponses pageServiceId(String pageServiceId) {
    this.pageServiceId = pageServiceId;
    return this;
  }

  /**
   * Get pageServiceId
   *
   * @return pageServiceId
   */
  @ApiModelProperty(value = "")
  public String getPageServiceId() {
    return pageServiceId;
  }

  public void setPageServiceId(String pageServiceId) {
    this.pageServiceId = pageServiceId;
  }

  public PageOperateResponses code(Long code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   *
   * @return code
   */
  @ApiModelProperty(value = "")
  public Long getCode() {
    return code;
  }

  public void setCode(Long code) {
    this.code = code;
  }

  public PageOperateResponses message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   *
   * @return message
   */
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageOperateResponses pageOperateResponses = (PageOperateResponses) o;
    return Objects.equals(this.pageServiceId, pageOperateResponses.pageServiceId)
        && Objects.equals(this.code, pageOperateResponses.code)
        && Objects.equals(this.message, pageOperateResponses.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageServiceId, code, message);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
