/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** POI规则 */
@ApiModel(description = "POI规则")
public class PoiRule {
  @SerializedName("region_id")
  private List<Long> regionId = null;

  @SerializedName("poi_category_id")
  private List<Long> poiCategoryId = null;

  @SerializedName("date_range")
  private DateRange dateRange = null;

  @SerializedName("day_of_week")
  private List<String> dayOfWeek = null;

  @SerializedName("frequency")
  private Long frequency = null;

  public PoiRule regionId(List<Long> regionId) {
    this.regionId = regionId;
    return this;
  }

  public PoiRule addRegionIdItem(Long regionIdItem) {
    if (this.regionId == null) {
      this.regionId = new ArrayList<Long>();
    }
    this.regionId.add(regionIdItem);
    return this;
  }

  /**
   * Get regionId
   *
   * @return regionId
   */
  @ApiModelProperty(value = "")
  public List<Long> getRegionId() {
    return regionId;
  }

  public void setRegionId(List<Long> regionId) {
    this.regionId = regionId;
  }

  public PoiRule poiCategoryId(List<Long> poiCategoryId) {
    this.poiCategoryId = poiCategoryId;
    return this;
  }

  public PoiRule addPoiCategoryIdItem(Long poiCategoryIdItem) {
    if (this.poiCategoryId == null) {
      this.poiCategoryId = new ArrayList<Long>();
    }
    this.poiCategoryId.add(poiCategoryIdItem);
    return this;
  }

  /**
   * Get poiCategoryId
   *
   * @return poiCategoryId
   */
  @ApiModelProperty(value = "")
  public List<Long> getPoiCategoryId() {
    return poiCategoryId;
  }

  public void setPoiCategoryId(List<Long> poiCategoryId) {
    this.poiCategoryId = poiCategoryId;
  }

  public PoiRule dateRange(DateRange dateRange) {
    this.dateRange = dateRange;
    return this;
  }

  /**
   * Get dateRange
   *
   * @return dateRange
   */
  @ApiModelProperty(value = "")
  public DateRange getDateRange() {
    return dateRange;
  }

  public void setDateRange(DateRange dateRange) {
    this.dateRange = dateRange;
  }

  public PoiRule dayOfWeek(List<String> dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
    return this;
  }

  public PoiRule addDayOfWeekItem(String dayOfWeekItem) {
    if (this.dayOfWeek == null) {
      this.dayOfWeek = new ArrayList<String>();
    }
    this.dayOfWeek.add(dayOfWeekItem);
    return this;
  }

  /**
   * Get dayOfWeek
   *
   * @return dayOfWeek
   */
  @ApiModelProperty(value = "")
  public List<String> getDayOfWeek() {
    return dayOfWeek;
  }

  public void setDayOfWeek(List<String> dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
  }

  public PoiRule frequency(Long frequency) {
    this.frequency = frequency;
    return this;
  }

  /**
   * Get frequency
   *
   * @return frequency
   */
  @ApiModelProperty(value = "")
  public Long getFrequency() {
    return frequency;
  }

  public void setFrequency(Long frequency) {
    this.frequency = frequency;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiRule poiRule = (PoiRule) o;
    return Objects.equals(this.regionId, poiRule.regionId)
        && Objects.equals(this.poiCategoryId, poiRule.poiCategoryId)
        && Objects.equals(this.dateRange, poiRule.dateRange)
        && Objects.equals(this.dayOfWeek, poiRule.dayOfWeek)
        && Objects.equals(this.frequency, poiRule.frequency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionId, poiCategoryId, dateRange, dayOfWeek, frequency);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
