/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** 调整尺寸 */
@ApiModel(description = "调整尺寸")
public class SizeAdjustment {
  @SerializedName("target_size")
  private SizeType targetSize = null;

  @SerializedName("size_adjustment_method")
  private SizeAdjustmentMethodEnum sizeAdjustmentMethod = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("bg_image_id1")
  private String bgImageId1 = null;

  @SerializedName("bg_image_id2")
  private String bgImageId2 = null;

  public SizeAdjustment targetSize(SizeType targetSize) {
    this.targetSize = targetSize;
    return this;
  }

  /**
   * Get targetSize
   *
   * @return targetSize
   */
  @ApiModelProperty(value = "")
  public SizeType getTargetSize() {
    return targetSize;
  }

  public void setTargetSize(SizeType targetSize) {
    this.targetSize = targetSize;
  }

  public SizeAdjustment sizeAdjustmentMethod(SizeAdjustmentMethodEnum sizeAdjustmentMethod) {
    this.sizeAdjustmentMethod = sizeAdjustmentMethod;
    return this;
  }

  /**
   * Get sizeAdjustmentMethod
   *
   * @return sizeAdjustmentMethod
   */
  @ApiModelProperty(value = "")
  public SizeAdjustmentMethodEnum getSizeAdjustmentMethod() {
    return sizeAdjustmentMethod;
  }

  public void setSizeAdjustmentMethod(SizeAdjustmentMethodEnum sizeAdjustmentMethod) {
    this.sizeAdjustmentMethod = sizeAdjustmentMethod;
  }

  public SizeAdjustment color(String color) {
    this.color = color;
    return this;
  }

  /**
   * Get color
   *
   * @return color
   */
  @ApiModelProperty(value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public SizeAdjustment bgImageId1(String bgImageId1) {
    this.bgImageId1 = bgImageId1;
    return this;
  }

  /**
   * Get bgImageId1
   *
   * @return bgImageId1
   */
  @ApiModelProperty(value = "")
  public String getBgImageId1() {
    return bgImageId1;
  }

  public void setBgImageId1(String bgImageId1) {
    this.bgImageId1 = bgImageId1;
  }

  public SizeAdjustment bgImageId2(String bgImageId2) {
    this.bgImageId2 = bgImageId2;
    return this;
  }

  /**
   * Get bgImageId2
   *
   * @return bgImageId2
   */
  @ApiModelProperty(value = "")
  public String getBgImageId2() {
    return bgImageId2;
  }

  public void setBgImageId2(String bgImageId2) {
    this.bgImageId2 = bgImageId2;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SizeAdjustment sizeAdjustment = (SizeAdjustment) o;
    return Objects.equals(this.targetSize, sizeAdjustment.targetSize)
        && Objects.equals(this.sizeAdjustmentMethod, sizeAdjustment.sizeAdjustmentMethod)
        && Objects.equals(this.color, sizeAdjustment.color)
        && Objects.equals(this.bgImageId1, sizeAdjustment.bgImageId1)
        && Objects.equals(this.bgImageId2, sizeAdjustment.bgImageId2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetSize, sizeAdjustmentMethod, color, bgImageId1, bgImageId2);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
