/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** 动态广告支持情况 */
@ApiModel(description = "动态广告支持情况")
public class SupportDynamicAbilitySpecList {
  @SerializedName("dynamic_ability_type")
  private List<String> dynamicAbilityType = null;

  @SerializedName("product_item_display_quantity")
  private List<String> productItemDisplayQuantity = null;

  public SupportDynamicAbilitySpecList dynamicAbilityType(List<String> dynamicAbilityType) {
    this.dynamicAbilityType = dynamicAbilityType;
    return this;
  }

  public SupportDynamicAbilitySpecList addDynamicAbilityTypeItem(String dynamicAbilityTypeItem) {
    if (this.dynamicAbilityType == null) {
      this.dynamicAbilityType = new ArrayList<String>();
    }
    this.dynamicAbilityType.add(dynamicAbilityTypeItem);
    return this;
  }

  /**
   * Get dynamicAbilityType
   *
   * @return dynamicAbilityType
   */
  @ApiModelProperty(value = "")
  public List<String> getDynamicAbilityType() {
    return dynamicAbilityType;
  }

  public void setDynamicAbilityType(List<String> dynamicAbilityType) {
    this.dynamicAbilityType = dynamicAbilityType;
  }

  public SupportDynamicAbilitySpecList productItemDisplayQuantity(
      List<String> productItemDisplayQuantity) {
    this.productItemDisplayQuantity = productItemDisplayQuantity;
    return this;
  }

  public SupportDynamicAbilitySpecList addProductItemDisplayQuantityItem(
      String productItemDisplayQuantityItem) {
    if (this.productItemDisplayQuantity == null) {
      this.productItemDisplayQuantity = new ArrayList<String>();
    }
    this.productItemDisplayQuantity.add(productItemDisplayQuantityItem);
    return this;
  }

  /**
   * Get productItemDisplayQuantity
   *
   * @return productItemDisplayQuantity
   */
  @ApiModelProperty(value = "")
  public List<String> getProductItemDisplayQuantity() {
    return productItemDisplayQuantity;
  }

  public void setProductItemDisplayQuantity(List<String> productItemDisplayQuantity) {
    this.productItemDisplayQuantity = productItemDisplayQuantity;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportDynamicAbilitySpecList supportDynamicAbilitySpecList = (SupportDynamicAbilitySpecList) o;
    return Objects.equals(this.dynamicAbilityType, supportDynamicAbilitySpecList.dynamicAbilityType)
        && Objects.equals(
            this.productItemDisplayQuantity,
            supportDynamicAbilitySpecList.productItemDisplayQuantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dynamicAbilityType, productItemDisplayQuantity);
  }

  @Override
  public String toString() {
    Gson gson = new Gson();
    return gson.toJson(this);
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
