/*
 * Marketing API
 * Marketing API
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tencent.ads.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** 授权类型(只读) */
@JsonAdapter(WechatAuthType.Adapter.class)
public enum WechatAuthType {
  DEFAULT("DEFAULT"),

  SAME_CORPORATION("SAME_CORPORATION"),

  OVER_CORPORATION("OVER_CORPORATION"),

  OVER_CORPORATION_SAME_GROUP("OVER_CORPORATION_SAME_GROUP"),

  OVER_CORPORATION_EMPLOYMENT("OVER_CORPORATION_EMPLOYMENT");

  private String value;

  WechatAuthType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WechatAuthType fromValue(String text) {
    for (WechatAuthType b : WechatAuthType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WechatAuthType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WechatAuthType enumeration)
        throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WechatAuthType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WechatAuthType.fromValue(String.valueOf(value));
    }
  }
}
